version: 2
updates:
  - package-ecosystem: gomod
    directories: ["/", "/tools"]
    schedule:
      interval: weekly
    groups:
      go:
        patterns: ["*"]
    labels: [dependencies]
    commit-message:
      prefix: "⬆️"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
    labels: [dependencies, ci]
    commit-message:
      prefix: "⬆️"

  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
    labels: [dependencies, packaging]
    commit-message:
      prefix: "⬆️"
