// Package testfixtures generates a small library of synthetic media for tests (movies, series,
// anime, music, subtitles, books, photos), with NFO files and local images. Everything comes from
// FFmpeg (lavfi sources) or from Go (books, photos): no copyrighted content, a reproducible result,
// about twenty MB.
//
// Tests get it through Library(t); the devtools/fixturegen command generates it by hand.
package testfixtures

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"golang.org/x/image/font/gofont/goregular"
)

// Version identifies the generated content. Bump it whenever the generator changes so that existing
// copies are regenerated.
const Version = "8"

// renamed is the version that gave every fixture a new name. A library generated before it is
// emptied first: none of its files would be replaced, and the tests would find both sets. Only a
// folder that carries the marker of an older generation is emptied, never one the generator did
// not write.
const renamed = 8

// Options configures the generation.
type Options struct {
	FFmpeg string
	Force  bool
	// Log receives one line per file created; nil means silent.
	Log func(string)
}

// changed lists, per version, the fixtures whose content changed: a library generated by an older
// version loses them before being completed (files that are present are otherwise kept as they
// are).
var changed = map[int][]string{}

// Generate writes the library into root. Files already there are kept (unless Force), except those
// changed by a version newer than the library's.
func Generate(ctx context.Context, root string, opts Options) (made, skipped int, err error) {
	if opts.FFmpeg == "" {
		opts.FFmpeg = "ffmpeg"
	}
	unlock, err := lockLibrary(root)
	if err != nil {
		return 0, 0, err
	}
	defer unlock()
	old := 0
	if v, err := os.ReadFile(filepath.Join(root, markerFile)); err == nil {
		old, _ = strconv.Atoi(strings.TrimSpace(string(v)))
	}
	if old > 0 && old < renamed {
		if err := empty(root); err != nil {
			return 0, 0, err
		}
	}
	for v, paths := range changed {
		if v <= old {
			continue
		}
		for _, p := range paths {
			if err := os.RemoveAll(filepath.Join(root, filepath.FromSlash(p))); err != nil {
				return 0, 0, err
			}
		}
	}
	g := &generator{root: root, ffmpeg: opts.FFmpeg, force: opts.Force, log: opts.Log}
	if err := g.run(ctx); err != nil {
		return g.made, g.skipped, err
	}
	return g.made, g.skipped, os.WriteFile(filepath.Join(root, markerFile), []byte(Version), 0o600)
}

// empty removes everything from the library except the lock file, which this process holds.
func empty(root string) error {
	entries, err := os.ReadDir(root)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if e.Name() == lockName {
			continue
		}
		if err := os.RemoveAll(filepath.Join(root, e.Name())); err != nil {
			return err
		}
	}
	return nil
}

// markerFile marks a complete generation, and its version.
const markerFile = ".fixtures-version"

// lockName is the file that reserves the library for one process at a time.
const lockName = ".generate.lock"

// lockLibrary reserves the library for this process until the returned function is called. Test
// packages run in parallel processes: without a lock, one deletes the fixtures of a stale version
// while another is writing them (marker not written yet).
func lockLibrary(root string) (unlock func(), err error) {
	if err := os.MkdirAll(root, 0o750); err != nil {
		return nil, err
	}
	f, err := os.OpenFile(filepath.Join(root, lockName), os.O_CREATE|os.O_RDWR, 0o600)
	if err != nil {
		return nil, err
	}
	if err := lockFile(f); err != nil {
		_ = f.Close()
		return nil, fmt.Errorf("locking the fixtures: %w", err)
	}
	return func() { _ = f.Close() }, nil
}

type generator struct {
	root    string
	ffmpeg  string
	force   bool
	log     func(string)
	made    int
	skipped int
	tmp     string
}

// Length of each video: enough for three chapters and several 4 s HLS segments.
const duration = "12"

func (g *generator) run(ctx context.Context) error {
	tmp, err := os.MkdirTemp("", "testfixtures-")
	if err != nil {
		return err
	}
	defer func() { _ = os.RemoveAll(tmp) }()
	g.tmp = tmp

	steps := []func(context.Context) error{g.movies, g.series, g.anime, g.music, g.subtitled, g.books, g.photos}
	for _, step := range steps {
		if err := step(ctx); err != nil {
			return err
		}
	}
	return nil
}

// Movies.

func (g *generator) movies(ctx context.Context) error {
	movies := filepath.Join(g.root, "Movies")

	// MP4 with H.264 and AAC: the simplest case, plays directly everywhere.
	dir := filepath.Join(movies, "Big Test Movie (2020)")
	if err := g.video(ctx, filepath.Join(dir, "Big Test Movie (2020).mp4"), videoSpec{
		source: "testsrc2=s=640x360:r=24", audio: []audioSpec{{freq: 440, lang: "eng"}},
	}); err != nil {
		return err
	}
	if err := g.movieExtras(ctx, dir, "Big Test Movie", 2020, "A test movie, as a plain MP4.", "Adventure"); err != nil {
		return err
	}

	// Multi-track MKV: two audio streams (French by default, Japanese), ASS and SRT subtitles,
	// chapters.
	dir = filepath.Join(movies, "Dual Audio (2019)")
	if err := g.video(ctx, filepath.Join(dir, "Dual Audio (2019).mkv"), videoSpec{
		source: "smptehdbars=s=640x360:r=24",
		audio:  []audioSpec{{freq: 330, lang: "fre", title: "French", isDefault: true}, {freq: 550, lang: "jpn", title: "日本語"}},
		subs:   []subSpec{{kind: "ass", lang: "fre", title: "French (ASS)"}, {kind: "srt", lang: "eng", title: "English"}},
		chapters: []chapter{
			{0, 3000, "OP"}, {3000, 9000, "Episode"}, {9000, 12000, "ED"},
		},
	}); err != nil {
		return err
	}
	if err := g.movieExtras(ctx, dir, "Dual Audio", 2019, "Two audio tracks, ASS and SRT subtitles, chapters.", "Animation"); err != nil {
		return err
	}

	// 10-bit HDR10 HEVC with 5.1 audio: forces transcoding in a browser.
	dir = filepath.Join(movies, "HDR Test (2021)")
	if err := g.video(ctx, filepath.Join(dir, "HDR Test (2021).mkv"), videoSpec{
		source: "testsrc2=s=640x360:r=24", hevcHDR: true,
		audio: []audioSpec{{freq: 220, lang: "eng", channels: 6}},
	}); err != nil {
		return err
	}
	if err := g.movieExtras(ctx, dir, "HDR Test", 2021, "10-bit HEVC in HDR10, 5.1 audio.", "Science Fiction"); err != nil {
		return err
	}

	// MKV without an index (Cues): a case where a player cannot seek in the file.
	dir = filepath.Join(movies, "Stream Dump (2018)")
	if err := g.video(ctx, filepath.Join(dir, "Stream Dump (2018).mkv"), videoSpec{
		source: "testsrc=s=640x360:r=24", audio: []audioSpec{{freq: 660, lang: "fre"}}, noCues: true,
	}); err != nil {
		return err
	}
	if err := g.movieExtras(ctx, dir, "Stream Dump", 2018, "Matroska written without an index (Cues).", "Drama"); err != nil {
		return err
	}

	// Two versions of the same movie in one folder.
	dir = filepath.Join(movies, "Versions (2017)")
	for _, v := range []struct{ name, size string }{{"1080p", "640x360"}, {"720p", "320x180"}} {
		if err := g.video(ctx, filepath.Join(dir, "Versions (2017) - "+v.name+".mp4"), videoSpec{
			source: "testsrc2=s=" + v.size + ":r=24", audio: []audioSpec{{freq: 440, lang: "fre"}},
		}); err != nil {
			return err
		}
	}
	return g.movieExtras(ctx, dir, "Versions", 2017, "A movie in two versions.", "Comedy")
}

func (g *generator) movieExtras(ctx context.Context, dir, title string, year int, plot, genre string) error {
	nfo := fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<movie>
  <title>%s</title>
  <year>%d</year>
  <plot>%s</plot>
  <genre>%s</genre>
  <runtime>1</runtime>
</movie>
`, title, year, plot, genre)
	if err := g.text(filepath.Join(dir, "movie.nfo"), nfo); err != nil {
		return err
	}
	if err := g.image(ctx, filepath.Join(dir, "poster.jpg"), "color=c=0x1e3a5f:s=400x600"); err != nil {
		return err
	}
	return g.image(ctx, filepath.Join(dir, "fanart.jpg"), "testsrc2=s=1280x720")
}

// Series and anime.

func (g *generator) series(ctx context.Context) error {
	show := filepath.Join(g.root, "Shows", "Café Stories (2022)")
	if err := g.text(filepath.Join(show, "tvshow.nfo"), `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<tvshow>
  <title>Café Stories</title>
  <year>2022</year>
  <plot>A test series: the same intro opens every episode.</plot>
  <genre>Drama</genre>
</tvshow>
`); err != nil {
		return err
	}
	if err := g.image(ctx, filepath.Join(show, "poster.jpg"), "color=c=0x5f1e3a:s=400x600"); err != nil {
		return err
	}
	episodes := []struct {
		season, episode int
		freq            int
	}{{1, 1, 300}, {1, 2, 350}, {1, 3, 400}, {2, 1, 450}}
	for _, ep := range episodes {
		name := fmt.Sprintf("Café Stories (2022) S%02dE%02d", ep.season, ep.episode)
		path := filepath.Join(show, fmt.Sprintf("Season %02d", ep.season), name+".mkv")
		if err := g.video(ctx, path, videoSpec{
			source: "testsrc2=s=640x360:r=24",
			// A shared 3 s intro (same melody), then content specific to each episode, and no
			// chapters: the intro can only be found by audio. The anime, on the other hand, has
			// named chapters.
			audio: []audioSpec{{freq: ep.freq, lang: "fre", sharedIntro: true}},
		}); err != nil {
			return err
		}
		nfo := fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<episodedetails>
  <title>Part %d</title>
  <season>%d</season>
  <episode>%d</episode>
  <plot>A test episode.</plot>
</episodedetails>
`, ep.episode, ep.season, ep.episode)
		if err := g.text(strings.TrimSuffix(path, ".mkv")+".nfo", nfo); err != nil {
			return err
		}
	}
	return nil
}

func (g *generator) anime(ctx context.Context) error {
	show := filepath.Join(g.root, "Anime", "Anime Test")
	for ep := 1; ep <= 3; ep++ {
		path := filepath.Join(show, fmt.Sprintf("[Group] Anime Test - %02d [1080p].mkv", ep))
		if err := g.video(ctx, path, videoSpec{
			source: "mandelbrot=s=640x360:r=24",
			audio: []audioSpec{
				{freq: 280 + 20*ep, lang: "jpn", title: "Japanese", isDefault: true, sharedIntro: true},
				{freq: 380 + 20*ep, lang: "fre", title: "French", sharedIntro: true},
			},
			subs:     []subSpec{{kind: "ass", lang: "fre", title: "French"}},
			chapters: []chapter{{0, 3000, "Opening"}, {3000, 9000, "Part A"}, {9000, 12000, "Ending"}},
		}); err != nil {
			return err
		}
	}
	return nil
}

// Music.

func (g *generator) music(ctx context.Context) error {
	album := filepath.Join(g.root, "Music", "Artist Test", "Album Test (2020)")
	cover := filepath.Join(album, "folder.jpg")
	if err := g.image(ctx, cover, "color=c=0x3a5f1e:s=600x600"); err != nil {
		return err
	}
	tracks := []struct {
		file, title, codec string
		n, freq            int
	}{
		{"01 - Track One.flac", "Track One", "flac", 1, 262},
		{"02 - Track Two.mp3", "Track Two", "libmp3lame", 2, 294},
	}
	for _, tr := range tracks {
		path := filepath.Join(album, tr.file)
		if g.exists(path) {
			continue
		}
		args := []string{
			"-f", "lavfi", "-i", fmt.Sprintf("sine=frequency=%d:sample_rate=44100:duration=%s", tr.freq, duration),
			"-i", cover, "-map", "0:a", "-map", "1:v",
			"-c:a", tr.codec, "-c:v", "mjpeg", "-disposition:v", "attached_pic",
			"-metadata", "title=" + tr.title, "-metadata", "artist=Artist Test",
			"-metadata", "album_artist=Artist Test", "-metadata", "album=Album Test",
			"-metadata", "date=2020", "-metadata", "genre=Electro", "-metadata", fmt.Sprintf("track=%d/2", tr.n),
		}
		if tr.codec == "libmp3lame" {
			args = append(args, "-id3v2_version", "3")
		}
		if err := g.ffmpegTo(ctx, path, args...); err != nil {
			return err
		}
	}
	return g.moreMusic(ctx)
}

// moreMusic completes the music library: NFO files for the artist and the album, an artist image, a
// two-disc album whose cover is only in the files (with a "feat." track and ReplayGain), and an
// untagged file at the root.
func (g *generator) moreMusic(ctx context.Context) error {
	artist := filepath.Join(g.root, "Music", "Artist Test")
	if err := g.image(ctx, filepath.Join(artist, "folder.jpg"), "color=c=0x7a1e5f:s=400x400"); err != nil {
		return err
	}
	if err := g.text(filepath.Join(artist, "artist.nfo"), `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<artist>
  <name>Artist Test</name>
  <biography>An artist made up for the tests.</biography>
  <genre>Electro</genre>
  <musicbrainzartistid>00000000-0000-0000-0000-00000000a001</musicbrainzartistid>
</artist>
`); err != nil {
		return err
	}
	if err := g.text(filepath.Join(artist, "Album Test (2020)", "album.nfo"), `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<album>
  <title>Album Test</title>
  <review>First album of the test artist.</review>
  <musicbrainzalbumid>00000000-0000-0000-0000-00000000b001</musicbrainzalbumid>
</album>
`); err != nil {
		return err
	}
	// Cover only in the files: a temporary image, outside the library.
	cover := filepath.Join(g.tmp, "second-cover.jpg")
	if err := g.image(ctx, cover, "color=c=0x1e3a5f:s=500x500"); err != nil {
		return err
	}
	second := filepath.Join(artist, "Double Album (2022)")
	tracks := []struct {
		dir, file, title, artist string
		disc, freq               int
		gain                     string
	}{
		{"CD1", "01 - First.flac", "First", "Artist Test", 1, 330, "-3.20 dB"},
		{"CD2", "01 - Second.flac", "Second", "Artist Test feat. Guest", 2, 349, "-4.10 dB"},
	}
	for _, tr := range tracks {
		path := filepath.Join(second, tr.dir, tr.file)
		if g.exists(path) {
			continue
		}
		if err := g.ffmpegTo(ctx, path,
			"-f", "lavfi", "-i", fmt.Sprintf("sine=frequency=%d:sample_rate=44100:duration=%s", tr.freq, duration),
			"-i", cover, "-map", "0:a", "-map", "1:v", "-c:a", "flac", "-c:v", "mjpeg", "-disposition:v", "attached_pic",
			"-metadata", "title="+tr.title, "-metadata", "artist="+tr.artist, "-metadata", "album_artist=Artist Test",
			"-metadata", "album=Double Album", "-metadata", "date=2022-05-13", "-metadata", "genre=Electro;Ambient",
			"-metadata", "track=1/1", "-metadata", fmt.Sprintf("disc=%d/2", tr.disc),
			"-metadata", "REPLAYGAIN_TRACK_GAIN="+tr.gain, "-metadata", "REPLAYGAIN_TRACK_PEAK=0.95",
		); err != nil {
			return err
		}
	}
	loose := filepath.Join(g.root, "Music", "Untagged.mp3")
	if g.exists(loose) {
		return nil
	}
	return g.ffmpegTo(ctx, loose,
		"-f", "lavfi", "-i", "sine=frequency=392:sample_rate=44100:duration="+duration,
		"-map_metadata", "-1", "-c:a", "libmp3lame", "-write_xing", "0", "-id3v2_version", "0")
}

// Building the FFmpeg commands.

type audioSpec struct {
	freq        int
	lang        string
	title       string
	channels    int
	isDefault   bool
	sharedIntro bool
}

type subSpec struct {
	kind  string // ass, srt or sup (PGS)
	lang  string
	title string
	// content replaces the default text (ass, srt).
	content string
}

// attachSpec is an attachment of a Matroska file (font).
type attachSpec struct {
	path, mime string
}

type chapter struct {
	startMs, endMs int
	title          string
}

type videoSpec struct {
	source   string
	audio    []audioSpec
	subs     []subSpec
	chapters []chapter
	hevcHDR  bool
	noCues   bool
	attach   []attachSpec
}

func (g *generator) video(ctx context.Context, path string, spec videoSpec) error {
	if g.exists(path) {
		return nil
	}
	// Not every lavfi source has a duration option (mandelbrot): cut on output.
	args := []string{"-f", "lavfi", "-i", spec.source}
	for _, a := range spec.audio {
		args = append(args, "-f", "lavfi", "-i", audioSource(a))
	}
	inputs := 1 + len(spec.audio)
	for i, s := range spec.subs {
		file, err := g.subtitleFile(s, i)
		if err != nil {
			return err
		}
		args = append(args, "-i", file)
	}
	metaInput := -1
	if len(spec.chapters) > 0 {
		file, err := g.chaptersFile(spec.chapters)
		if err != nil {
			return err
		}
		metaInput = inputs + len(spec.subs)
		args = append(args, "-f", "ffmetadata", "-i", file)
	}

	args = append(args, "-map", "0:v")
	for i := range spec.audio {
		args = append(args, "-map", fmt.Sprintf("%d:a", i+1))
	}
	for i := range spec.subs {
		args = append(args, "-map", fmt.Sprintf("%d:s", inputs+i))
	}
	// Global metadata and chapter titles are taken from the ffmetadata file (which only holds the
	// chapters). Without chapters, no metadata is inherited from the sources.
	if metaInput >= 0 {
		args = append(args, "-map_chapters", fmt.Sprint(metaInput), "-map_metadata", fmt.Sprint(metaInput))
	} else {
		args = append(args, "-map_metadata", "-1")
	}
	args = append(args, "-t", duration)

	if spec.hevcHDR {
		// Color metadata is set on the frames (setparams): otherwise recent FFmpeg versions
		// overwrite it with that of the source (unspecified).
		args = append(args, "-vf", "format=yuv420p10le,setparams=color_primaries=bt2020:color_trc=smpte2084:colorspace=bt2020nc:range=tv",
			"-c:v", "libx265", "-preset", "ultrafast", "-tag:v", "hvc1",
			"-x265-params", "log-level=error:hdr10=1:colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc:"+
				"master-display=G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1):max-cll=1000,400")
	} else {
		args = append(args, "-c:v", "libx264", "-preset", "veryfast", "-profile:v", "high", "-pix_fmt", "yuv420p", "-g", "48")
	}
	for i, a := range spec.audio {
		codec := "aac"
		if a.channels == 6 {
			codec = "eac3"
		}
		args = append(args, fmt.Sprintf("-c:a:%d", i), codec, fmt.Sprintf("-metadata:s:a:%d", i), "language="+a.lang)
		if a.title != "" {
			args = append(args, fmt.Sprintf("-metadata:s:a:%d", i), "title="+a.title)
		}
		disposition := "0"
		if a.isDefault {
			disposition = "default"
		}
		args = append(args, fmt.Sprintf("-disposition:a:%d", i), disposition)
	}
	if len(spec.subs) > 0 {
		args = append(args, "-c:s", "copy")
		for i, s := range spec.subs {
			args = append(args, fmt.Sprintf("-metadata:s:s:%d", i), "language="+s.lang,
				fmt.Sprintf("-metadata:s:s:%d", i), "title="+s.title)
		}
	}
	for i, a := range spec.attach {
		args = append(args, "-attach", a.path, fmt.Sprintf("-metadata:s:t:%d", i), "mimetype="+a.mime,
			fmt.Sprintf("-metadata:s:t:%d", i), "filename="+filepath.Base(a.path))
	}
	if strings.HasSuffix(path, ".mp4") {
		args = append(args, "-movflags", "+faststart")
	}
	if spec.noCues {
		// Matroska "live" mode: no index (Cues) and no complete seek table.
		args = append(args, "-live", "1")
	}
	if err := g.ffmpegTo(ctx, path, args...); err != nil {
		return err
	}
	if spec.noCues {
		return checkNoCues(path)
	}
	return nil
}

func audioSource(a audioSpec) string {
	layout := "stereo"
	if a.channels == 6 {
		layout = "5.1"
	}
	if !a.sharedIntro {
		return fmt.Sprintf("sine=frequency=%d:sample_rate=48000:duration=%s,aformat=channel_layouts=%s", a.freq, duration, layout)
	}
	// A shared 3 s melody (notes changing every 0.5 s), then the episode's own frequency.
	expr := fmt.Sprintf("if(lt(t,3), 0.4*sin(2*PI*t*(523+100*floor(2*t))), 0.4*sin(2*PI*%d*t))", a.freq)
	return fmt.Sprintf("aevalsrc='%s':s=48000:d=%s,aformat=channel_layouts=%s", expr, duration, layout)
}

func (g *generator) subtitleFile(s subSpec, i int) (string, error) {
	path := filepath.Join(g.tmp, fmt.Sprintf("sub%d-%d.%s", i, len(s.content), s.kind))
	var content string
	switch {
	case s.kind == "sup":
		return path, os.WriteFile(path, pgs(640, 480, pgsEvents), 0o600)
	case s.content != "":
		content = s.content
	}
	switch {
	case content != "":
	case s.kind == "ass":
		content = `[Script Info]
ScriptType: v4.00+
PlayResX: 640
PlayResY: 360

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,28,&H00FFFFFF,&H000000FF,&H00000000,&H64000000,0,0,0,0,100,100,0,0,1,2,0,2,10,10,20,1
Style: Title,Arial,36,&H0000FFFF,&H000000FF,&H00000000,&H64000000,1,0,0,0,100,100,0,0,1,3,0,8,10,10,20,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.50,0:00:02.50,Title,,0,0,0,,{\fad(200,200)}Opening
Dialogue: 0,0:00:04.00,0:00:07.00,Default,,0,0,0,,First line, with accents: é à ç.
Dialogue: 0,0:00:08.00,0:00:11.00,Default,,0,0,0,,Second line.
`
	case s.kind == "srt":
		content = `1
00:00:04,000 --> 00:00:07,000
First line.

2
00:00:08,000 --> 00:00:11,000
Second line.
`
	default:
		return "", fmt.Errorf("unknown subtitle kind: %s", s.kind)
	}
	return path, os.WriteFile(path, []byte(content), 0o600)
}

// Subtitles.

// pgsEvents are the lines of the test PGS, drawn on 640 x 480 for a 640 x 360 video (cropped movie:
// the black bars were removed from the video, not from the subtitles). The first one sits in the
// bottom bar and is only visible if burn-in puts the bars back; the second is inside the picture.
var pgsEvents = []pgsEvent{
	{start: 4 * time.Second, end: 7 * time.Second, x: 220, y: 425, w: 200, h: 40},
	{start: 8 * time.Second, end: 11 * time.Second, x: 220, y: 300, w: 200, h: 40},
}

// fansubASS is a fansub-style ASS subtitle using the Go font (attached to the file): dialogue, a
// top line, a positioned sign, a karaoke effect, a drawing.
const fansubASS = `[Script Info]
ScriptType: v4.00+
PlayResX: 640
PlayResY: 360

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Go,40,&H00FFFFFF,&H000000FF,&H00000000,&H64000000,0,0,0,0,100,100,0,0,1,2,0,2,10,10,20,1
Style: Sign,Go,24,&H0000FFFF,&H000000FF,&H00000000,&H64000000,1,0,0,0,100,100,0,0,1,0,0,5,10,10,20,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.00,0:00:03.00,Default,,0,0,0,,{\an8}At the top
Dialogue: 0,0:00:04.00,0:00:07.00,Default,,0,0,0,,A line in {\i1}italics{\i0}.
Dialogue: 0,0:00:04.00,0:00:11.00,Sign,,0,0,0,,{\pos(320,60)}RAMEN
Dialogue: 1,0:00:08.00,0:00:08.30,Default,,0,0,0,fx,{\move(100,300,200,300)\k30}ka
Dialogue: 0,0:00:08.00,0:00:11.00,Default,,0,0,0,,Second line.
`

// subtitled makes a movie with all sorts of subtitles: styled ASS with its attached font, SRT, PGS,
// and external subtitles (SubRip in UTF-8 with a BOM, forced SubRip in Windows-1252, PGS). It lives
// in a separate folder, because the movie tests count their own.
func (g *generator) subtitled(ctx context.Context) error {
	dir := filepath.Join(g.root, "Subtitles", "Fonts (2022)")
	font := filepath.Join(g.tmp, "GoRegular.ttf")
	if err := os.WriteFile(font, goregular.TTF, 0o600); err != nil {
		return err
	}
	if err := g.video(ctx, filepath.Join(dir, "Fonts (2022).mkv"), videoSpec{
		source: "testsrc2=s=640x360:r=24",
		audio:  []audioSpec{{freq: 440, lang: "jpn", isDefault: true}},
		subs: []subSpec{
			{kind: "ass", lang: "fre", title: "French", content: fansubASS},
			{kind: "srt", lang: "eng", title: "English"},
			{kind: "sup", lang: "fre", title: "French (PGS)"},
		},
		attach: []attachSpec{{path: font, mime: "application/x-truetype-font"}},
	}); err != nil {
		return err
	}
	for name, content := range map[string]string{
		"Fonts (2022).fr.srt":        "\ufeff1\n00:00:04,000 --> 00:00:07,000\nFirst line, é à ç.\n",
		"Fonts (2022).en.forced.srt": "1\r\n00:00:01,000 --> 00:00:02,000\r\nCaf\xe9!\r\n",
		"Fonts (2022).de.sup":        string(pgs(640, 480, pgsEvents)),
	} {
		if err := g.text(filepath.Join(dir, name), content); err != nil {
			return err
		}
	}
	return nil
}

func (g *generator) chaptersFile(chapters []chapter) (string, error) {
	var b strings.Builder
	b.WriteString(";FFMETADATA1\n")
	for _, c := range chapters {
		fmt.Fprintf(&b, "[CHAPTER]\nTIMEBASE=1/1000\nSTART=%d\nEND=%d\ntitle=%s\n", c.startMs, c.endMs, c.title)
	}
	path := filepath.Join(g.tmp, fmt.Sprintf("chapters-%d.txt", len(chapters)))
	return path, os.WriteFile(path, []byte(b.String()), 0o600)
}

func (g *generator) image(ctx context.Context, path, source string) error {
	if g.exists(path) {
		return nil
	}
	return g.ffmpegTo(ctx, path, "-f", "lavfi", "-i", source, "-frames:v", "1", "-q:v", "4")
}

func (g *generator) text(path, content string) error {
	if g.exists(path) {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return err
	}
	g.made++
	return os.WriteFile(path, []byte(content), 0o600)
}

func (g *generator) exists(path string) bool {
	if g.force {
		return false
	}
	if _, err := os.Stat(path); err == nil {
		g.skipped++
		return true
	}
	return false
}

// ffmpegTo runs ffmpeg into a temporary file that is only renamed on success: never a half-written
// fixture.
func (g *generator) ffmpegTo(ctx context.Context, path string, args ...string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return err
	}
	// Temporary name specific to the process: several test packages may generate at the same time,
	// and the final rename replaces atomically.
	partial := filepath.Join(filepath.Dir(path), fmt.Sprintf(".partial-%d-%s", os.Getpid(), filepath.Base(path)))
	full := append([]string{
		"-hide_banner", "-loglevel", "error", "-y",
		"-fflags", "+bitexact", "-flags", "+bitexact",
	}, args...)
	// The format is taken from the extension of the final file, not from the temporary name.
	full = append(full, "-f", muxerFor(path), partial)
	cmd := exec.CommandContext(ctx, g.ffmpeg, full...) //nolint:gosec // test tool, arguments built here
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		_ = os.Remove(partial)
		return fmt.Errorf("%s: %w\n%s", filepath.Base(path), err, stderr.String())
	}
	g.made++
	if g.log != nil {
		g.log(path)
	}
	return os.Rename(partial, path)
}

func muxerFor(path string) string {
	switch strings.ToLower(filepath.Ext(path)) {
	case ".mkv":
		return "matroska"
	case ".mp4":
		return "mp4"
	case ".flac":
		return "flac"
	case ".mp3":
		return "mp3"
	case ".jpg":
		return "image2"
	default:
		return strings.TrimPrefix(filepath.Ext(path), ".")
	}
}

// checkNoCues checks that the Matroska file has no Cues element (ID 0x1C53BB6B).
func checkNoCues(path string) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	if bytes.Contains(raw, []byte{0x1C, 0x53, 0xBB, 0x6B}) {
		return errors.New(filepath.Base(path) + " has an index (Cues): the -live option did not do what was expected")
	}
	return nil
}
