// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/laterna-project/laterna/internal/domain"
)

const countAccounts = `-- name: CountAccounts :one
SELECT count(*) FROM accounts
`

func (q *Queries) CountAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnabledAdmins = `-- name: CountEnabledAdmins :one
SELECT count(*) FROM accounts WHERE is_admin = 1 AND disabled = 0
`

func (q *Queries) CountEnabledAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnabledAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProfiles = `-- name: CountProfiles :one
SELECT count(*) FROM profiles WHERE account_id = ?
`

func (q *Queries) CountProfiles(ctx context.Context, accountID domain.ID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProfiles, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, id domain.ID) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const deleteAccountLibraries = `-- name: DeleteAccountLibraries :exec
DELETE FROM account_libraries WHERE account_id = ?
`

func (q *Queries) DeleteAccountLibraries(ctx context.Context, accountID domain.ID) error {
	_, err := q.db.ExecContext(ctx, deleteAccountLibraries, accountID)
	return err
}

const deleteAccountSessions = `-- name: DeleteAccountSessions :exec
DELETE FROM sessions WHERE account_id = ?
`

func (q *Queries) DeleteAccountSessions(ctx context.Context, accountID domain.ID) error {
	_, err := q.db.ExecContext(ctx, deleteAccountSessions, accountID)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOtherSessions = `-- name: DeleteOtherSessions :exec
DELETE FROM sessions WHERE account_id = ? AND id <> ?
`

type DeleteOtherSessionsParams struct {
	AccountID domain.ID
	ID        domain.ID
}

func (q *Queries) DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteOtherSessions, arg.AccountID, arg.ID)
	return err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles WHERE id = ?
`

func (q *Queries) DeleteProfile(ctx context.Context, id domain.ID) error {
	_, err := q.db.ExecContext(ctx, deleteProfile, id)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id domain.ID) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, username, username_key, password_hash, is_admin, disabled, created_at, updated_at, all_libraries, max_age, block_unrated, deny_downloads FROM accounts WHERE id = ?
`

func (q *Queries) GetAccount(ctx context.Context, id domain.ID) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameKey,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AllLibraries,
		&i.MaxAge,
		&i.BlockUnrated,
		&i.DenyDownloads,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, username, username_key, password_hash, is_admin, disabled, created_at, updated_at, all_libraries, max_age, block_unrated, deny_downloads FROM accounts WHERE username_key = ?
`

func (q *Queries) GetAccountByUsername(ctx context.Context, usernameKey string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByUsername, usernameKey)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameKey,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AllLibraries,
		&i.MaxAge,
		&i.BlockUnrated,
		&i.DenyDownloads,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT id, account_id, name, name_key, pin_hash, kid, created_at, updated_at, max_age, block_unrated, theme_id, theme_mode, language FROM profiles WHERE id = ?
`

func (q *Queries) GetProfile(ctx context.Context, id domain.ID) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.NameKey,
		&i.PinHash,
		&i.Kid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAge,
		&i.BlockUnrated,
		&i.ThemeID,
		&i.ThemeMode,
		&i.Language,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, account_id, profile_id, token_hash, device_name, client, client_version, platform, created_at, last_used_at, expires_at, last_ip FROM sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id domain.ID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ProfileID,
		&i.TokenHash,
		&i.DeviceName,
		&i.Client,
		&i.ClientVersion,
		&i.Platform,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.LastIp,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, account_id, profile_id, token_hash, device_name, client, client_version, platform, created_at, last_used_at, expires_at, last_ip FROM sessions WHERE token_hash = ?
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ProfileID,
		&i.TokenHash,
		&i.DeviceName,
		&i.Client,
		&i.ClientVersion,
		&i.Platform,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.LastIp,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO accounts (id, username, username_key, password_hash, is_admin, disabled, all_libraries, max_age,
                      block_unrated, deny_downloads, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, 0, ?, ?, ?, ?, ?, ?)
`

type InsertAccountParams struct {
	ID            domain.ID
	Username      string
	UsernameKey   string
	PasswordHash  string
	IsAdmin       int64
	AllLibraries  int64
	MaxAge        sql.NullInt64
	BlockUnrated  int64
	DenyDownloads int64
	CreatedAt     int64
	UpdatedAt     int64
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.ExecContext(ctx, insertAccount,
		arg.ID,
		arg.Username,
		arg.UsernameKey,
		arg.PasswordHash,
		arg.IsAdmin,
		arg.AllLibraries,
		arg.MaxAge,
		arg.BlockUnrated,
		arg.DenyDownloads,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertAccountLibrary = `-- name: InsertAccountLibrary :exec
INSERT INTO account_libraries (account_id, library_id) VALUES (?, ?) ON CONFLICT DO NOTHING
`

type InsertAccountLibraryParams struct {
	AccountID domain.ID
	LibraryID domain.ID
}

func (q *Queries) InsertAccountLibrary(ctx context.Context, arg InsertAccountLibraryParams) error {
	_, err := q.db.ExecContext(ctx, insertAccountLibrary, arg.AccountID, arg.LibraryID)
	return err
}

const insertProfile = `-- name: InsertProfile :exec
INSERT INTO profiles (id, account_id, name, name_key, pin_hash, kid, max_age, block_unrated, language, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertProfileParams struct {
	ID           domain.ID
	AccountID    domain.ID
	Name         string
	NameKey      string
	PinHash      sql.NullString
	Kid          int64
	MaxAge       sql.NullInt64
	BlockUnrated int64
	Language     string
	CreatedAt    int64
	UpdatedAt    int64
}

func (q *Queries) InsertProfile(ctx context.Context, arg InsertProfileParams) error {
	_, err := q.db.ExecContext(ctx, insertProfile,
		arg.ID,
		arg.AccountID,
		arg.Name,
		arg.NameKey,
		arg.PinHash,
		arg.Kid,
		arg.MaxAge,
		arg.BlockUnrated,
		arg.Language,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id, account_id, profile_id, token_hash, device_name, client, client_version, platform,
                      created_at, last_used_at, expires_at, last_ip)
VALUES (?, ?, NULL, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSessionParams struct {
	ID            domain.ID
	AccountID     domain.ID
	TokenHash     string
	DeviceName    string
	Client        string
	ClientVersion string
	Platform      string
	CreatedAt     int64
	LastUsedAt    int64
	ExpiresAt     int64
	LastIp        string
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.ID,
		arg.AccountID,
		arg.TokenHash,
		arg.DeviceName,
		arg.Client,
		arg.ClientVersion,
		arg.Platform,
		arg.CreatedAt,
		arg.LastUsedAt,
		arg.ExpiresAt,
		arg.LastIp,
	)
	return err
}

const listAccountLibraries = `-- name: ListAccountLibraries :many
SELECT library_id FROM account_libraries WHERE account_id = ?
`

func (q *Queries) ListAccountLibraries(ctx context.Context, accountID domain.ID) ([]domain.ID, error) {
	rows, err := q.db.QueryContext(ctx, listAccountLibraries, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []domain.ID{}
	for rows.Next() {
		var library_id domain.ID
		if err := rows.Scan(&library_id); err != nil {
			return nil, err
		}
		items = append(items, library_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountSummaries = `-- name: ListAccountSummaries :many
SELECT a.id, a.username, a.username_key, a.password_hash, a.is_admin, a.disabled, a.created_at, a.updated_at, a.all_libraries, a.max_age, a.block_unrated, a.deny_downloads,
       (SELECT count(*) FROM profiles p WHERE p.account_id = a.id) AS profile_count,
       CAST(coalesce((SELECT max(s.last_used_at) FROM sessions s WHERE s.account_id = a.id), 0) AS INTEGER) AS last_active
FROM accounts a
ORDER BY a.created_at, a.id
`

type ListAccountSummariesRow struct {
	ID            domain.ID
	Username      string
	UsernameKey   string
	PasswordHash  string
	IsAdmin       int64
	Disabled      int64
	CreatedAt     int64
	UpdatedAt     int64
	AllLibraries  int64
	MaxAge        sql.NullInt64
	BlockUnrated  int64
	DenyDownloads int64
	ProfileCount  int64
	LastActive    int64
}

func (q *Queries) ListAccountSummaries(ctx context.Context) ([]ListAccountSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccountSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountSummariesRow{}
	for rows.Next() {
		var i ListAccountSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.UsernameKey,
			&i.PasswordHash,
			&i.IsAdmin,
			&i.Disabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AllLibraries,
			&i.MaxAge,
			&i.BlockUnrated,
			&i.DenyDownloads,
			&i.ProfileCount,
			&i.LastActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAccountLibraries = `-- name: ListAllAccountLibraries :many
SELECT account_id, library_id FROM account_libraries
`

func (q *Queries) ListAllAccountLibraries(ctx context.Context) ([]AccountLibrary, error) {
	rows, err := q.db.QueryContext(ctx, listAllAccountLibraries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountLibrary{}
	for rows.Next() {
		var i AccountLibrary
		if err := rows.Scan(&i.AccountID, &i.LibraryID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, account_id, name, name_key, pin_hash, kid, created_at, updated_at, max_age, block_unrated, theme_id, theme_mode, language FROM profiles WHERE account_id = ? ORDER BY created_at, id
`

func (q *Queries) ListProfiles(ctx context.Context, accountID domain.ID) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, listProfiles, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Profile{}
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.NameKey,
			&i.PinHash,
			&i.Kid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaxAge,
			&i.BlockUnrated,
			&i.ThemeID,
			&i.ThemeMode,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, account_id, profile_id, token_hash, device_name, client, client_version, platform, created_at, last_used_at, expires_at, last_ip FROM sessions WHERE account_id = ? AND expires_at > ? ORDER BY last_used_at DESC, id
`

type ListSessionsParams struct {
	AccountID domain.ID
	ExpiresAt int64
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions, arg.AccountID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ProfileID,
			&i.TokenHash,
			&i.DeviceName,
			&i.Client,
			&i.ClientVersion,
			&i.Platform,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.LastIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSessionProfile = `-- name: SetSessionProfile :exec
UPDATE sessions SET profile_id = ? WHERE id = ?
`

type SetSessionProfileParams struct {
	ProfileID *domain.ID
	ID        domain.ID
}

func (q *Queries) SetSessionProfile(ctx context.Context, arg SetSessionProfileParams) error {
	_, err := q.db.ExecContext(ctx, setSessionProfile, arg.ProfileID, arg.ID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_used_at = ?, expires_at = ?, last_ip = ? WHERE id = ?
`

type TouchSessionParams struct {
	LastUsedAt int64
	ExpiresAt  int64
	LastIp     string
	ID         domain.ID
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession,
		arg.LastUsedAt,
		arg.ExpiresAt,
		arg.LastIp,
		arg.ID,
	)
	return err
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE accounts
SET username = ?, username_key = ?, is_admin = ?, disabled = ?, all_libraries = ?, max_age = ?, block_unrated = ?,
    deny_downloads = ?, updated_at = ?
WHERE id = ?
`

type UpdateAccountParams struct {
	Username      string
	UsernameKey   string
	IsAdmin       int64
	Disabled      int64
	AllLibraries  int64
	MaxAge        sql.NullInt64
	BlockUnrated  int64
	DenyDownloads int64
	UpdatedAt     int64
	ID            domain.ID
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.ExecContext(ctx, updateAccount,
		arg.Username,
		arg.UsernameKey,
		arg.IsAdmin,
		arg.Disabled,
		arg.AllLibraries,
		arg.MaxAge,
		arg.BlockUnrated,
		arg.DenyDownloads,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateAccountPassword = `-- name: UpdateAccountPassword :exec
UPDATE accounts SET password_hash = ?, updated_at = ? WHERE id = ?
`

type UpdateAccountPasswordParams struct {
	PasswordHash string
	UpdatedAt    int64
	ID           domain.ID
}

func (q *Queries) UpdateAccountPassword(ctx context.Context, arg UpdateAccountPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountPassword, arg.PasswordHash, arg.UpdatedAt, arg.ID)
	return err
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE profiles
SET name = ?, name_key = ?, pin_hash = ?, kid = ?, max_age = ?, block_unrated = ?, language = ?, updated_at = ?
WHERE id = ?
`

type UpdateProfileParams struct {
	Name         string
	NameKey      string
	PinHash      sql.NullString
	Kid          int64
	MaxAge       sql.NullInt64
	BlockUnrated int64
	Language     string
	UpdatedAt    int64
	ID           domain.ID
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateProfile,
		arg.Name,
		arg.NameKey,
		arg.PinHash,
		arg.Kid,
		arg.MaxAge,
		arg.BlockUnrated,
		arg.Language,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
