// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlc

import (
	"context"

	"github.com/laterna-project/laterna/internal/domain"
)

const deleteActivityBefore = `-- name: DeleteActivityBefore :execrows
DELETE FROM activity WHERE at < ?
`

func (q *Queries) DeleteActivityBefore(ctx context.Context, at int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteActivityBefore, at)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteFailedJob = `-- name: DeleteFailedJob :exec
DELETE FROM jobs WHERE id = ? AND state = 'failed'
`

func (q *Queries) DeleteFailedJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFailedJob, id)
	return err
}

const getFailedJob = `-- name: GetFailedJob :one
SELECT id, kind, target FROM jobs WHERE id = ? AND state = 'failed'
`

type GetFailedJobRow struct {
	ID     int64
	Kind   string
	Target string
}

func (q *Queries) GetFailedJob(ctx context.Context, id int64) (GetFailedJobRow, error) {
	row := q.db.QueryRowContext(ctx, getFailedJob, id)
	var i GetFailedJobRow
	err := row.Scan(&i.ID, &i.Kind, &i.Target)
	return i, err
}

const insertActivity = `-- name: InsertActivity :exec
INSERT INTO activity (at, kind, warning, account_id, profile_id, item_id, message) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertActivityParams struct {
	At        int64
	Kind      string
	Warning   int64
	AccountID *domain.ID
	ProfileID *domain.ID
	ItemID    *domain.ID
	Message   string
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) error {
	_, err := q.db.ExecContext(ctx, insertActivity,
		arg.At,
		arg.Kind,
		arg.Warning,
		arg.AccountID,
		arg.ProfileID,
		arg.ItemID,
		arg.Message,
	)
	return err
}

const listAllSessions = `-- name: ListAllSessions :many
SELECT s.id, s.account_id, s.profile_id, s.token_hash, s.device_name, s.client, s.client_version, s.platform, s.created_at, s.last_used_at, s.expires_at, s.last_ip, a.username, CAST(coalesce(p.name, '') AS TEXT) AS profile_name
FROM sessions s
JOIN accounts a ON a.id = s.account_id
LEFT JOIN profiles p ON p.id = s.profile_id
WHERE s.expires_at > ?
ORDER BY s.last_used_at DESC, s.id
`

type ListAllSessionsRow struct {
	ID            domain.ID
	AccountID     domain.ID
	ProfileID     *domain.ID
	TokenHash     string
	DeviceName    string
	Client        string
	ClientVersion string
	Platform      string
	CreatedAt     int64
	LastUsedAt    int64
	ExpiresAt     int64
	LastIp        string
	Username      string
	ProfileName   string
}

func (q *Queries) ListAllSessions(ctx context.Context, expiresAt int64) ([]ListAllSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllSessions, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSessionsRow{}
	for rows.Next() {
		var i ListAllSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ProfileID,
			&i.TokenHash,
			&i.DeviceName,
			&i.Client,
			&i.ClientVersion,
			&i.Platform,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.LastIp,
			&i.Username,
			&i.ProfileName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailedJobs = `-- name: ListFailedJobs :many
SELECT id, kind, target, attempts, last_error, updated_at
FROM jobs
WHERE state = 'failed'
ORDER BY updated_at DESC, id DESC
LIMIT ?
`

type ListFailedJobsRow struct {
	ID        int64
	Kind      string
	Target    string
	Attempts  int64
	LastError string
	UpdatedAt int64
}

func (q *Queries) ListFailedJobs(ctx context.Context, limit int64) ([]ListFailedJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFailedJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFailedJobsRow{}
	for rows.Next() {
		var i ListFailedJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Target,
			&i.Attempts,
			&i.LastError,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
