// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: books.sql

package sqlc

import (
	"context"

	"github.com/laterna-project/laterna/internal/domain"
)

const deleteEmptyBookSeries = `-- name: DeleteEmptyBookSeries :execrows
DELETE FROM items
WHERE items.library_id = ? AND items.kind = 'book_series'
  AND NOT EXISTS (SELECT 1 FROM items b WHERE b.parent_id = items.id)
`

func (q *Queries) DeleteEmptyBookSeries(ctx context.Context, libraryID domain.ID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEmptyBookSeries, libraryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteReadingProgress = `-- name: DeleteReadingProgress :exec
DELETE FROM reading_progress WHERE profile_id = ? AND item_id = ?
`

type DeleteReadingProgressParams struct {
	ProfileID domain.ID
	ItemID    domain.ID
}

func (q *Queries) DeleteReadingProgress(ctx context.Context, arg DeleteReadingProgressParams) error {
	_, err := q.db.ExecContext(ctx, deleteReadingProgress, arg.ProfileID, arg.ItemID)
	return err
}

const firstBookOfSeries = `-- name: FirstBookOfSeries :one
SELECT i.id
FROM items i
JOIN books b ON b.item_id = i.id
WHERE i.parent_id = ? AND i.kind = 'book' AND EXISTS (
    SELECT 1 FROM item_files l JOIN media_files f ON f.id = l.file_id
    WHERE l.item_id = i.id AND f.missing_since IS NULL
)
ORDER BY b.number, i.sort_title
LIMIT 1
`

func (q *Queries) FirstBookOfSeries(ctx context.Context, parentID *domain.ID) (domain.ID, error) {
	row := q.db.QueryRowContext(ctx, firstBookOfSeries, parentID)
	var id domain.ID
	err := row.Scan(&id)
	return id, err
}

const getBook = `-- name: GetBook :one
SELECT item_id, number, publisher, language, isbn FROM books WHERE item_id = ?
`

func (q *Queries) GetBook(ctx context.Context, itemID domain.ID) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBook, itemID)
	var i Book
	err := row.Scan(
		&i.ItemID,
		&i.Number,
		&i.Publisher,
		&i.Language,
		&i.Isbn,
	)
	return i, err
}

const getBookFile = `-- name: GetBookFile :one
SELECT file_id, format, layout, right_to_left, page_count, pages, access_key FROM book_files WHERE file_id = ?
`

func (q *Queries) GetBookFile(ctx context.Context, fileID domain.ID) (BookFile, error) {
	row := q.db.QueryRowContext(ctx, getBookFile, fileID)
	var i BookFile
	err := row.Scan(
		&i.FileID,
		&i.Format,
		&i.Layout,
		&i.RightToLeft,
		&i.PageCount,
		&i.Pages,
		&i.AccessKey,
	)
	return i, err
}

const getReadingProgress = `-- name: GetReadingProgress :one
SELECT profile_id, item_id, page, locator, progression, updated_at FROM reading_progress WHERE profile_id = ? AND item_id = ?
`

type GetReadingProgressParams struct {
	ProfileID domain.ID
	ItemID    domain.ID
}

func (q *Queries) GetReadingProgress(ctx context.Context, arg GetReadingProgressParams) (ReadingProgress, error) {
	row := q.db.QueryRowContext(ctx, getReadingProgress, arg.ProfileID, arg.ItemID)
	var i ReadingProgress
	err := row.Scan(
		&i.ProfileID,
		&i.ItemID,
		&i.Page,
		&i.Locator,
		&i.Progression,
		&i.UpdatedAt,
	)
	return i, err
}

const listSeriesBookIDs = `-- name: ListSeriesBookIDs :many
SELECT i.id
FROM items i
JOIN books b ON b.item_id = i.id
WHERE i.parent_id = ? AND i.kind = 'book'
ORDER BY b.number, i.sort_title
`

func (q *Queries) ListSeriesBookIDs(ctx context.Context, parentID *domain.ID) ([]domain.ID, error) {
	rows, err := q.db.QueryContext(ctx, listSeriesBookIDs, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []domain.ID{}
	for rows.Next() {
		var id domain.ID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBook = `-- name: UpsertBook :exec

INSERT INTO books (item_id, number, publisher, language, isbn)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (item_id) DO UPDATE
SET number = excluded.number,
    publisher = excluded.publisher,
    language = excluded.language,
    isbn = excluded.isbn
`

type UpsertBookParams struct {
	ItemID    domain.ID
	Number    float64
	Publisher string
	Language  string
	Isbn      string
}

// Books: books, book files, reading progress.
func (q *Queries) UpsertBook(ctx context.Context, arg UpsertBookParams) error {
	_, err := q.db.ExecContext(ctx, upsertBook,
		arg.ItemID,
		arg.Number,
		arg.Publisher,
		arg.Language,
		arg.Isbn,
	)
	return err
}

const upsertBookFile = `-- name: UpsertBookFile :exec
INSERT INTO book_files (file_id, format, layout, right_to_left, page_count, pages, access_key)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (file_id) DO UPDATE
SET format = excluded.format,
    layout = excluded.layout,
    right_to_left = excluded.right_to_left,
    page_count = excluded.page_count,
    pages = excluded.pages,
    access_key = excluded.access_key
`

type UpsertBookFileParams struct {
	FileID      domain.ID
	Format      string
	Layout      string
	RightToLeft int64
	PageCount   int64
	Pages       string
	AccessKey   string
}

func (q *Queries) UpsertBookFile(ctx context.Context, arg UpsertBookFileParams) error {
	_, err := q.db.ExecContext(ctx, upsertBookFile,
		arg.FileID,
		arg.Format,
		arg.Layout,
		arg.RightToLeft,
		arg.PageCount,
		arg.Pages,
		arg.AccessKey,
	)
	return err
}

const upsertReadingProgress = `-- name: UpsertReadingProgress :exec
INSERT INTO reading_progress (profile_id, item_id, page, locator, progression, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (profile_id, item_id) DO UPDATE
SET page = excluded.page,
    locator = excluded.locator,
    progression = excluded.progression,
    updated_at = excluded.updated_at
`

type UpsertReadingProgressParams struct {
	ProfileID   domain.ID
	ItemID      domain.ID
	Page        int64
	Locator     string
	Progression float64
	UpdatedAt   int64
}

func (q *Queries) UpsertReadingProgress(ctx context.Context, arg UpsertReadingProgressParams) error {
	_, err := q.db.ExecContext(ctx, upsertReadingProgress,
		arg.ProfileID,
		arg.ItemID,
		arg.Page,
		arg.Locator,
		arg.Progression,
		arg.UpdatedAt,
	)
	return err
}
