// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/laterna-project/laterna/internal/domain"
)

const getUserData = `-- name: GetUserData :one
SELECT played, play_count, position_ms, last_played_at, favorite FROM user_data WHERE profile_id = ? AND item_id = ?
`

type GetUserDataParams struct {
	ProfileID domain.ID
	ItemID    domain.ID
}

type GetUserDataRow struct {
	Played       int64
	PlayCount    int64
	PositionMs   int64
	LastPlayedAt sql.NullInt64
	Favorite     int64
}

func (q *Queries) GetUserData(ctx context.Context, arg GetUserDataParams) (GetUserDataRow, error) {
	row := q.db.QueryRowContext(ctx, getUserData, arg.ProfileID, arg.ItemID)
	var i GetUserDataRow
	err := row.Scan(
		&i.Played,
		&i.PlayCount,
		&i.PositionMs,
		&i.LastPlayedAt,
		&i.Favorite,
	)
	return i, err
}

const listSeasonEpisodeIDs = `-- name: ListSeasonEpisodeIDs :many
SELECT item_id FROM episodes WHERE season_id = ?
`

func (q *Queries) ListSeasonEpisodeIDs(ctx context.Context, seasonID domain.ID) ([]domain.ID, error) {
	rows, err := q.db.QueryContext(ctx, listSeasonEpisodeIDs, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []domain.ID{}
	for rows.Next() {
		var item_id domain.ID
		if err := rows.Scan(&item_id); err != nil {
			return nil, err
		}
		items = append(items, item_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasonIDs = `-- name: ListSeasonIDs :many
SELECT item_id FROM seasons WHERE series_id = ? ORDER BY number
`

func (q *Queries) ListSeasonIDs(ctx context.Context, seriesID domain.ID) ([]domain.ID, error) {
	rows, err := q.db.QueryContext(ctx, listSeasonIDs, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []domain.ID{}
	for rows.Next() {
		var item_id domain.ID
		if err := rows.Scan(&item_id); err != nil {
			return nil, err
		}
		items = append(items, item_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesEpisodeIDs = `-- name: ListSeriesEpisodeIDs :many
SELECT item_id FROM episodes WHERE series_id = ?
`

func (q *Queries) ListSeriesEpisodeIDs(ctx context.Context, seriesID domain.ID) ([]domain.ID, error) {
	rows, err := q.db.QueryContext(ctx, listSeriesEpisodeIDs, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []domain.ID{}
	for rows.Next() {
		var item_id domain.ID
		if err := rows.Scan(&item_id); err != nil {
			return nil, err
		}
		items = append(items, item_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveFinished = `-- name: SaveFinished :exec
INSERT INTO user_data (profile_id, item_id, played, play_count, position_ms, last_played_at, updated_at)
VALUES (?, ?, 1, 1, 0, ?, ?)
ON CONFLICT (profile_id, item_id) DO UPDATE
SET played = 1,
    play_count = user_data.play_count + 1,
    position_ms = 0,
    last_played_at = excluded.last_played_at,
    updated_at = excluded.updated_at
`

type SaveFinishedParams struct {
	ProfileID    domain.ID
	ItemID       domain.ID
	LastPlayedAt sql.NullInt64
	UpdatedAt    int64
}

func (q *Queries) SaveFinished(ctx context.Context, arg SaveFinishedParams) error {
	_, err := q.db.ExecContext(ctx, saveFinished,
		arg.ProfileID,
		arg.ItemID,
		arg.LastPlayedAt,
		arg.UpdatedAt,
	)
	return err
}

const saveResumePosition = `-- name: SaveResumePosition :exec
INSERT INTO user_data (profile_id, item_id, position_ms, last_played_at, updated_at) VALUES (?, ?, ?, ?, ?)
ON CONFLICT (profile_id, item_id) DO UPDATE
SET position_ms = excluded.position_ms,
    last_played_at = excluded.last_played_at,
    updated_at = excluded.updated_at
`

type SaveResumePositionParams struct {
	ProfileID    domain.ID
	ItemID       domain.ID
	PositionMs   int64
	LastPlayedAt sql.NullInt64
	UpdatedAt    int64
}

func (q *Queries) SaveResumePosition(ctx context.Context, arg SaveResumePositionParams) error {
	_, err := q.db.ExecContext(ctx, saveResumePosition,
		arg.ProfileID,
		arg.ItemID,
		arg.PositionMs,
		arg.LastPlayedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertFavorite = `-- name: UpsertFavorite :exec
INSERT INTO user_data (profile_id, item_id, favorite, updated_at) VALUES (?, ?, ?, ?)
ON CONFLICT (profile_id, item_id) DO UPDATE
SET favorite = excluded.favorite, updated_at = excluded.updated_at
`

type UpsertFavoriteParams struct {
	ProfileID domain.ID
	ItemID    domain.ID
	Favorite  int64
	UpdatedAt int64
}

func (q *Queries) UpsertFavorite(ctx context.Context, arg UpsertFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, upsertFavorite,
		arg.ProfileID,
		arg.ItemID,
		arg.Favorite,
		arg.UpdatedAt,
	)
	return err
}

const upsertPlayed = `-- name: UpsertPlayed :exec
INSERT INTO user_data (profile_id, item_id, played, position_ms, last_played_at, updated_at)
VALUES (?, ?, ?, 0, ?, ?)
ON CONFLICT (profile_id, item_id) DO UPDATE
SET played = excluded.played,
    position_ms = 0,
    last_played_at = COALESCE(excluded.last_played_at, user_data.last_played_at),
    updated_at = excluded.updated_at
`

type UpsertPlayedParams struct {
	ProfileID    domain.ID
	ItemID       domain.ID
	Played       int64
	LastPlayedAt sql.NullInt64
	UpdatedAt    int64
}

func (q *Queries) UpsertPlayed(ctx context.Context, arg UpsertPlayedParams) error {
	_, err := q.db.ExecContext(ctx, upsertPlayed,
		arg.ProfileID,
		arg.ItemID,
		arg.Played,
		arg.LastPlayedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertUserData = `-- name: UpsertUserData :exec
INSERT INTO user_data (profile_id, item_id, played, play_count, position_ms, last_played_at, favorite, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (profile_id, item_id) DO UPDATE
SET played = excluded.played,
    play_count = excluded.play_count,
    position_ms = excluded.position_ms,
    last_played_at = excluded.last_played_at,
    favorite = excluded.favorite,
    updated_at = excluded.updated_at
`

type UpsertUserDataParams struct {
	ProfileID    domain.ID
	ItemID       domain.ID
	Played       int64
	PlayCount    int64
	PositionMs   int64
	LastPlayedAt sql.NullInt64
	Favorite     int64
	UpdatedAt    int64
}

func (q *Queries) UpsertUserData(ctx context.Context, arg UpsertUserDataParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserData,
		arg.ProfileID,
		arg.ItemID,
		arg.Played,
		arg.PlayCount,
		arg.PositionMs,
		arg.LastPlayedAt,
		arg.Favorite,
		arg.UpdatedAt,
	)
	return err
}
