// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collections.sql

package sqlc

import (
	"context"

	"github.com/laterna-project/laterna/internal/domain"
)

const countProfilePlaylists = `-- name: CountProfilePlaylists :one
SELECT count(*) FROM playlists WHERE profile_id = ?
`

func (q *Queries) CountProfilePlaylists(ctx context.Context, profileID domain.ID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProfilePlaylists, profileID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections WHERE id = ?
`

func (q *Queries) DeleteCollection(ctx context.Context, id domain.ID) error {
	_, err := q.db.ExecContext(ctx, deleteCollection, id)
	return err
}

const deleteCollectionItem = `-- name: DeleteCollectionItem :exec
DELETE FROM collection_items WHERE collection_id = ? AND item_id = ?
`

type DeleteCollectionItemParams struct {
	CollectionID domain.ID
	ItemID       domain.ID
}

func (q *Queries) DeleteCollectionItem(ctx context.Context, arg DeleteCollectionItemParams) error {
	_, err := q.db.ExecContext(ctx, deleteCollectionItem, arg.CollectionID, arg.ItemID)
	return err
}

const deleteEmptyNFOCollections = `-- name: DeleteEmptyNFOCollections :execrows
DELETE FROM collections
WHERE nfo_key <> '' AND NOT EXISTS (SELECT 1 FROM collection_items ci WHERE ci.collection_id = collections.id)
`

func (q *Queries) DeleteEmptyNFOCollections(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEmptyNFOCollections)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteItemFromOtherNFOCollections = `-- name: DeleteItemFromOtherNFOCollections :exec
DELETE FROM collection_items
WHERE item_id = ?1
  AND collection_id IN (SELECT c.id FROM collections c WHERE c.nfo_key <> '' AND c.nfo_key <> ?2)
`

type DeleteItemFromOtherNFOCollectionsParams struct {
	ItemID  domain.ID
	KeepKey string
}

func (q *Queries) DeleteItemFromOtherNFOCollections(ctx context.Context, arg DeleteItemFromOtherNFOCollectionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteItemFromOtherNFOCollections, arg.ItemID, arg.KeepKey)
	return err
}

const deletePlaylist = `-- name: DeletePlaylist :exec
DELETE FROM playlists WHERE id = ?
`

func (q *Queries) DeletePlaylist(ctx context.Context, id domain.ID) error {
	_, err := q.db.ExecContext(ctx, deletePlaylist, id)
	return err
}

const deletePlaylistEntry = `-- name: DeletePlaylistEntry :exec
DELETE FROM playlist_entries WHERE id = ? AND playlist_id = ?
`

type DeletePlaylistEntryParams struct {
	ID         domain.ID
	PlaylistID domain.ID
}

func (q *Queries) DeletePlaylistEntry(ctx context.Context, arg DeletePlaylistEntryParams) error {
	_, err := q.db.ExecContext(ctx, deletePlaylistEntry, arg.ID, arg.PlaylistID)
	return err
}

const getCollection = `-- name: GetCollection :one
SELECT id, name, overview, nfo_key, created_at, updated_at FROM collections WHERE id = ?
`

func (q *Queries) GetCollection(ctx context.Context, id domain.ID) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollection, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Overview,
		&i.NfoKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCollectionByNFOKey = `-- name: GetCollectionByNFOKey :one
SELECT id, name, overview, nfo_key, created_at, updated_at FROM collections WHERE nfo_key = ?
`

func (q *Queries) GetCollectionByNFOKey(ctx context.Context, nfoKey string) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollectionByNFOKey, nfoKey)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Overview,
		&i.NfoKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaylist = `-- name: GetPlaylist :one
SELECT id, profile_id, name, created_at, updated_at FROM playlists WHERE id = ?
`

func (q *Queries) GetPlaylist(ctx context.Context, id domain.ID) (Playlist, error) {
	row := q.db.QueryRowContext(ctx, getPlaylist, id)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCollection = `-- name: InsertCollection :exec
INSERT INTO collections (id, name, overview, nfo_key, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertCollectionParams struct {
	ID        domain.ID
	Name      string
	Overview  string
	NfoKey    string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) InsertCollection(ctx context.Context, arg InsertCollectionParams) error {
	_, err := q.db.ExecContext(ctx, insertCollection,
		arg.ID,
		arg.Name,
		arg.Overview,
		arg.NfoKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertCollectionItem = `-- name: InsertCollectionItem :exec
INSERT INTO collection_items (collection_id, item_id, added_at) VALUES (?, ?, ?) ON CONFLICT DO NOTHING
`

type InsertCollectionItemParams struct {
	CollectionID domain.ID
	ItemID       domain.ID
	AddedAt      int64
}

func (q *Queries) InsertCollectionItem(ctx context.Context, arg InsertCollectionItemParams) error {
	_, err := q.db.ExecContext(ctx, insertCollectionItem, arg.CollectionID, arg.ItemID, arg.AddedAt)
	return err
}

const insertPlaylist = `-- name: InsertPlaylist :exec
INSERT INTO playlists (id, profile_id, name, created_at, updated_at) VALUES (?, ?, ?, ?, ?)
`

type InsertPlaylistParams struct {
	ID        domain.ID
	ProfileID domain.ID
	Name      string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) InsertPlaylist(ctx context.Context, arg InsertPlaylistParams) error {
	_, err := q.db.ExecContext(ctx, insertPlaylist,
		arg.ID,
		arg.ProfileID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertPlaylistEntry = `-- name: InsertPlaylistEntry :exec
INSERT INTO playlist_entries (id, playlist_id, item_id, position, added_at) VALUES (?, ?, ?, ?, ?)
`

type InsertPlaylistEntryParams struct {
	ID         domain.ID
	PlaylistID domain.ID
	ItemID     domain.ID
	Position   int64
	AddedAt    int64
}

func (q *Queries) InsertPlaylistEntry(ctx context.Context, arg InsertPlaylistEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertPlaylistEntry,
		arg.ID,
		arg.PlaylistID,
		arg.ItemID,
		arg.Position,
		arg.AddedAt,
	)
	return err
}

const listItemCollections = `-- name: ListItemCollections :many
SELECT c.id, c.name, c.overview, c.nfo_key, c.created_at, c.updated_at FROM collections c JOIN collection_items ci ON ci.collection_id = c.id WHERE ci.item_id = ? ORDER BY c.name
`

func (q *Queries) ListItemCollections(ctx context.Context, itemID domain.ID) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, listItemCollections, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Overview,
			&i.NfoKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistEntries = `-- name: ListPlaylistEntries :many
SELECT id, item_id, position FROM playlist_entries WHERE playlist_id = ? ORDER BY position
`

type ListPlaylistEntriesRow struct {
	ID       domain.ID
	ItemID   domain.ID
	Position int64
}

func (q *Queries) ListPlaylistEntries(ctx context.Context, playlistID domain.ID) ([]ListPlaylistEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylistEntries, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaylistEntriesRow{}
	for rows.Next() {
		var i ListPlaylistEntriesRow
		if err := rows.Scan(&i.ID, &i.ItemID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfilePlaylists = `-- name: ListProfilePlaylists :many
SELECT id, profile_id, name, created_at, updated_at FROM playlists WHERE profile_id = ? ORDER BY updated_at DESC, id
`

func (q *Queries) ListProfilePlaylists(ctx context.Context, profileID domain.ID) ([]Playlist, error) {
	rows, err := q.db.QueryContext(ctx, listProfilePlaylists, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Playlist{}
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renamePlaylist = `-- name: RenamePlaylist :exec
UPDATE playlists SET name = ?, updated_at = ? WHERE id = ?
`

type RenamePlaylistParams struct {
	Name      string
	UpdatedAt int64
	ID        domain.ID
}

func (q *Queries) RenamePlaylist(ctx context.Context, arg RenamePlaylistParams) error {
	_, err := q.db.ExecContext(ctx, renamePlaylist, arg.Name, arg.UpdatedAt, arg.ID)
	return err
}

const setPlaylistEntryPosition = `-- name: SetPlaylistEntryPosition :exec
UPDATE playlist_entries SET position = ? WHERE id = ?
`

type SetPlaylistEntryPositionParams struct {
	Position int64
	ID       domain.ID
}

func (q *Queries) SetPlaylistEntryPosition(ctx context.Context, arg SetPlaylistEntryPositionParams) error {
	_, err := q.db.ExecContext(ctx, setPlaylistEntryPosition, arg.Position, arg.ID)
	return err
}

const touchPlaylist = `-- name: TouchPlaylist :exec
UPDATE playlists SET updated_at = ? WHERE id = ?
`

type TouchPlaylistParams struct {
	UpdatedAt int64
	ID        domain.ID
}

func (q *Queries) TouchPlaylist(ctx context.Context, arg TouchPlaylistParams) error {
	_, err := q.db.ExecContext(ctx, touchPlaylist, arg.UpdatedAt, arg.ID)
	return err
}

const updateCollection = `-- name: UpdateCollection :exec
UPDATE collections SET name = ?, overview = ?, updated_at = ? WHERE id = ?
`

type UpdateCollectionParams struct {
	Name      string
	Overview  string
	UpdatedAt int64
	ID        domain.ID
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) error {
	_, err := q.db.ExecContext(ctx, updateCollection,
		arg.Name,
		arg.Overview,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
