// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: downloads.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/laterna-project/laterna/internal/domain"
)

const countSessionDownloads = `-- name: CountSessionDownloads :one
SELECT count(*) FROM downloads WHERE session_id = ?
`

func (q *Queries) CountSessionDownloads(ctx context.Context, sessionID domain.ID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessionDownloads, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDownload = `-- name: DeleteDownload :exec
DELETE FROM downloads WHERE id = ?
`

func (q *Queries) DeleteDownload(ctx context.Context, id domain.ID) error {
	_, err := q.db.ExecContext(ctx, deleteDownload, id)
	return err
}

const deleteOfflinePlaysBefore = `-- name: DeleteOfflinePlaysBefore :exec
DELETE FROM offline_plays WHERE played_at < ?
`

func (q *Queries) DeleteOfflinePlaysBefore(ctx context.Context, playedAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteOfflinePlaysBefore, playedAt)
	return err
}

const deleteOldDownloads = `-- name: DeleteOldDownloads :execrows
DELETE FROM downloads
WHERE (state = 'ready' AND ready_at < ?1) OR (state = 'failed' AND updated_at < ?1)
`

func (q *Queries) DeleteOldDownloads(ctx context.Context, cutoff sql.NullInt64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOldDownloads, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDownload = `-- name: GetDownload :one
SELECT id, account_id, profile_id, session_id, item_id, file_id, quality, state, "plan", progress, estimate, size, path, error, created_at, updated_at, ready_at FROM downloads WHERE id = ?
`

func (q *Queries) GetDownload(ctx context.Context, id domain.ID) (Download, error) {
	row := q.db.QueryRowContext(ctx, getDownload, id)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ProfileID,
		&i.SessionID,
		&i.ItemID,
		&i.FileID,
		&i.Quality,
		&i.State,
		&i.Plan,
		&i.Progress,
		&i.Estimate,
		&i.Size,
		&i.Path,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadyAt,
	)
	return i, err
}

const insertDownload = `-- name: InsertDownload :exec

INSERT INTO downloads (id, account_id, profile_id, session_id, item_id, file_id, quality, state, plan, progress,
                       estimate, size, path, error, created_at, updated_at, ready_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDownloadParams struct {
	ID        domain.ID
	AccountID domain.ID
	ProfileID domain.ID
	SessionID domain.ID
	ItemID    domain.ID
	FileID    domain.ID
	Quality   string
	State     string
	Plan      string
	Progress  float64
	Estimate  int64
	Size      int64
	Path      string
	Error     string
	CreatedAt int64
	UpdatedAt int64
	ReadyAt   sql.NullInt64
}

// Offline downloads.
func (q *Queries) InsertDownload(ctx context.Context, arg InsertDownloadParams) error {
	_, err := q.db.ExecContext(ctx, insertDownload,
		arg.ID,
		arg.AccountID,
		arg.ProfileID,
		arg.SessionID,
		arg.ItemID,
		arg.FileID,
		arg.Quality,
		arg.State,
		arg.Plan,
		arg.Progress,
		arg.Estimate,
		arg.Size,
		arg.Path,
		arg.Error,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ReadyAt,
	)
	return err
}

const insertOfflinePlay = `-- name: InsertOfflinePlay :execrows
INSERT INTO offline_plays (profile_id, item_id, played_at) VALUES (?, ?, ?) ON CONFLICT DO NOTHING
`

type InsertOfflinePlayParams struct {
	ProfileID domain.ID
	ItemID    domain.ID
	PlayedAt  int64
}

func (q *Queries) InsertOfflinePlay(ctx context.Context, arg InsertOfflinePlayParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertOfflinePlay, arg.ProfileID, arg.ItemID, arg.PlayedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listDownloadIDs = `-- name: ListDownloadIDs :many
SELECT id FROM downloads
`

func (q *Queries) ListDownloadIDs(ctx context.Context) ([]domain.ID, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []domain.ID{}
	for rows.Next() {
		var id domain.ID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionDownloads = `-- name: ListSessionDownloads :many
SELECT id, account_id, profile_id, session_id, item_id, file_id, quality, state, "plan", progress, estimate, size, path, error, created_at, updated_at, ready_at FROM downloads WHERE session_id = ? AND profile_id = ? ORDER BY created_at, id
`

type ListSessionDownloadsParams struct {
	SessionID domain.ID
	ProfileID domain.ID
}

func (q *Queries) ListSessionDownloads(ctx context.Context, arg ListSessionDownloadsParams) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, listSessionDownloads, arg.SessionID, arg.ProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Download{}
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ProfileID,
			&i.SessionID,
			&i.ItemID,
			&i.FileID,
			&i.Quality,
			&i.State,
			&i.Plan,
			&i.Progress,
			&i.Estimate,
			&i.Size,
			&i.Path,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReadyAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveOfflineFinished = `-- name: SaveOfflineFinished :exec
INSERT INTO user_data (profile_id, item_id, played, play_count, position_ms, last_played_at, updated_at)
VALUES (?, ?, 1, 1, 0, ?, ?)
ON CONFLICT (profile_id, item_id) DO UPDATE
SET played = 1,
    play_count = user_data.play_count + 1,
    position_ms = CASE WHEN excluded.last_played_at >= coalesce(user_data.last_played_at, 0) THEN 0 ELSE user_data.position_ms END,
    last_played_at = max(coalesce(user_data.last_played_at, 0), excluded.last_played_at),
    updated_at = excluded.updated_at
`

type SaveOfflineFinishedParams struct {
	ProfileID    domain.ID
	ItemID       domain.ID
	LastPlayedAt sql.NullInt64
	UpdatedAt    int64
}

func (q *Queries) SaveOfflineFinished(ctx context.Context, arg SaveOfflineFinishedParams) error {
	_, err := q.db.ExecContext(ctx, saveOfflineFinished,
		arg.ProfileID,
		arg.ItemID,
		arg.LastPlayedAt,
		arg.UpdatedAt,
	)
	return err
}

const saveOfflinePosition = `-- name: SaveOfflinePosition :exec
INSERT INTO user_data (profile_id, item_id, position_ms, last_played_at, updated_at) VALUES (?, ?, ?, ?, ?)
ON CONFLICT (profile_id, item_id) DO UPDATE
SET position_ms = excluded.position_ms,
    last_played_at = excluded.last_played_at,
    updated_at = excluded.updated_at
WHERE excluded.last_played_at > coalesce(user_data.last_played_at, 0)
`

type SaveOfflinePositionParams struct {
	ProfileID    domain.ID
	ItemID       domain.ID
	PositionMs   int64
	LastPlayedAt sql.NullInt64
	UpdatedAt    int64
}

func (q *Queries) SaveOfflinePosition(ctx context.Context, arg SaveOfflinePositionParams) error {
	_, err := q.db.ExecContext(ctx, saveOfflinePosition,
		arg.ProfileID,
		arg.ItemID,
		arg.PositionMs,
		arg.LastPlayedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateDownloadProgress = `-- name: UpdateDownloadProgress :exec
UPDATE downloads SET progress = ?, updated_at = ? WHERE id = ? AND state = 'preparing'
`

type UpdateDownloadProgressParams struct {
	Progress  float64
	UpdatedAt int64
	ID        domain.ID
}

func (q *Queries) UpdateDownloadProgress(ctx context.Context, arg UpdateDownloadProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateDownloadProgress, arg.Progress, arg.UpdatedAt, arg.ID)
	return err
}

const updateDownloadState = `-- name: UpdateDownloadState :exec
UPDATE downloads
SET state = ?, progress = ?, size = ?, path = ?, error = ?, ready_at = ?, updated_at = ?
WHERE id = ?
`

type UpdateDownloadStateParams struct {
	State     string
	Progress  float64
	Size      int64
	Path      string
	Error     string
	ReadyAt   sql.NullInt64
	UpdatedAt int64
	ID        domain.ID
}

func (q *Queries) UpdateDownloadState(ctx context.Context, arg UpdateDownloadStateParams) error {
	_, err := q.db.ExecContext(ctx, updateDownloadState,
		arg.State,
		arg.Progress,
		arg.Size,
		arg.Path,
		arg.Error,
		arg.ReadyAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
