// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/laterna-project/laterna/internal/domain"
)

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM media_files WHERE id = ?
`

func (q *Queries) DeleteFile(ctx context.Context, id domain.ID) error {
	_, err := q.db.ExecContext(ctx, deleteFile, id)
	return err
}

const deleteFileChapters = `-- name: DeleteFileChapters :exec
DELETE FROM chapters WHERE file_id = ?
`

func (q *Queries) DeleteFileChapters(ctx context.Context, fileID domain.ID) error {
	_, err := q.db.ExecContext(ctx, deleteFileChapters, fileID)
	return err
}

const deleteFileStreams = `-- name: DeleteFileStreams :exec
DELETE FROM media_streams WHERE file_id = ?
`

func (q *Queries) DeleteFileStreams(ctx context.Context, fileID domain.ID) error {
	_, err := q.db.ExecContext(ctx, deleteFileStreams, fileID)
	return err
}

const getFile = `-- name: GetFile :one
SELECT id, library_id, path, size, mtime, fingerprint, missing_since, analyzed_at, analysis_error, container, duration_ms, bitrate, created_at, updated_at, tags FROM media_files WHERE id = ?
`

func (q *Queries) GetFile(ctx context.Context, id domain.ID) (MediaFile, error) {
	row := q.db.QueryRowContext(ctx, getFile, id)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Path,
		&i.Size,
		&i.Mtime,
		&i.Fingerprint,
		&i.MissingSince,
		&i.AnalyzedAt,
		&i.AnalysisError,
		&i.Container,
		&i.DurationMs,
		&i.Bitrate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
	)
	return i, err
}

const getTrickplay = `-- name: GetTrickplay :one
SELECT file_id, fingerprint, "key", interval_ms, width, height, columns, "rows", count, sheets, created_at FROM trickplay WHERE file_id = ?
`

func (q *Queries) GetTrickplay(ctx context.Context, fileID domain.ID) (Trickplay, error) {
	row := q.db.QueryRowContext(ctx, getTrickplay, fileID)
	var i Trickplay
	err := row.Scan(
		&i.FileID,
		&i.Fingerprint,
		&i.Key,
		&i.IntervalMs,
		&i.Width,
		&i.Height,
		&i.Columns,
		&i.Rows,
		&i.Count,
		&i.Sheets,
		&i.CreatedAt,
	)
	return i, err
}

const insertChapter = `-- name: InsertChapter :exec
INSERT INTO chapters (file_id, idx, start_ms, end_ms, title) VALUES (?, ?, ?, ?, ?)
`

type InsertChapterParams struct {
	FileID  domain.ID
	Idx     int64
	StartMs int64
	EndMs   int64
	Title   string
}

func (q *Queries) InsertChapter(ctx context.Context, arg InsertChapterParams) error {
	_, err := q.db.ExecContext(ctx, insertChapter,
		arg.FileID,
		arg.Idx,
		arg.StartMs,
		arg.EndMs,
		arg.Title,
	)
	return err
}

const insertFile = `-- name: InsertFile :exec
INSERT INTO media_files (id, library_id, path, size, mtime, fingerprint, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertFileParams struct {
	ID          domain.ID
	LibraryID   domain.ID
	Path        string
	Size        int64
	Mtime       int64
	Fingerprint string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) error {
	_, err := q.db.ExecContext(ctx, insertFile,
		arg.ID,
		arg.LibraryID,
		arg.Path,
		arg.Size,
		arg.Mtime,
		arg.Fingerprint,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertStream = `-- name: InsertStream :exec
INSERT INTO media_streams (file_id, idx, kind, codec, profile, language, title, is_default, is_forced,
                           is_hearing_impaired, width, height, bit_depth, frame_rate, dynamic_range,
                           pixel_format, channels, channel_layout, sample_rate, bitrate)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertStreamParams struct {
	FileID            domain.ID
	Idx               int64
	Kind              string
	Codec             string
	Profile           string
	Language          string
	Title             string
	IsDefault         int64
	IsForced          int64
	IsHearingImpaired int64
	Width             int64
	Height            int64
	BitDepth          int64
	FrameRate         float64
	DynamicRange      string
	PixelFormat       string
	Channels          int64
	ChannelLayout     string
	SampleRate        int64
	Bitrate           int64
}

func (q *Queries) InsertStream(ctx context.Context, arg InsertStreamParams) error {
	_, err := q.db.ExecContext(ctx, insertStream,
		arg.FileID,
		arg.Idx,
		arg.Kind,
		arg.Codec,
		arg.Profile,
		arg.Language,
		arg.Title,
		arg.IsDefault,
		arg.IsForced,
		arg.IsHearingImpaired,
		arg.Width,
		arg.Height,
		arg.BitDepth,
		arg.FrameRate,
		arg.DynamicRange,
		arg.PixelFormat,
		arg.Channels,
		arg.ChannelLayout,
		arg.SampleRate,
		arg.Bitrate,
	)
	return err
}

const listFileChapters = `-- name: ListFileChapters :many
SELECT file_id, idx, start_ms, end_ms, title FROM chapters WHERE file_id = ? ORDER BY idx
`

func (q *Queries) ListFileChapters(ctx context.Context, fileID domain.ID) ([]Chapter, error) {
	rows, err := q.db.QueryContext(ctx, listFileChapters, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chapter{}
	for rows.Next() {
		var i Chapter
		if err := rows.Scan(
			&i.FileID,
			&i.Idx,
			&i.StartMs,
			&i.EndMs,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileStreams = `-- name: ListFileStreams :many
SELECT file_id, idx, kind, codec, profile, language, title, is_default, is_forced, is_hearing_impaired, width, height, bit_depth, frame_rate, dynamic_range, pixel_format, channels, channel_layout, sample_rate, bitrate FROM media_streams WHERE file_id = ? ORDER BY idx
`

func (q *Queries) ListFileStreams(ctx context.Context, fileID domain.ID) ([]MediaStream, error) {
	rows, err := q.db.QueryContext(ctx, listFileStreams, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaStream{}
	for rows.Next() {
		var i MediaStream
		if err := rows.Scan(
			&i.FileID,
			&i.Idx,
			&i.Kind,
			&i.Codec,
			&i.Profile,
			&i.Language,
			&i.Title,
			&i.IsDefault,
			&i.IsForced,
			&i.IsHearingImpaired,
			&i.Width,
			&i.Height,
			&i.BitDepth,
			&i.FrameRate,
			&i.DynamicRange,
			&i.PixelFormat,
			&i.Channels,
			&i.ChannelLayout,
			&i.SampleRate,
			&i.Bitrate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesMissingBefore = `-- name: ListFilesMissingBefore :many
SELECT id FROM media_files WHERE library_id = ? AND missing_since IS NOT NULL AND missing_since < ?
`

type ListFilesMissingBeforeParams struct {
	LibraryID    domain.ID
	MissingSince sql.NullInt64
}

func (q *Queries) ListFilesMissingBefore(ctx context.Context, arg ListFilesMissingBeforeParams) ([]domain.ID, error) {
	rows, err := q.db.QueryContext(ctx, listFilesMissingBefore, arg.LibraryID, arg.MissingSince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []domain.ID{}
	for rows.Next() {
		var id domain.ID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraryFiles = `-- name: ListLibraryFiles :many
SELECT f.id, f.path, f.size, f.mtime, f.fingerprint, f.missing_since, f.analyzed_at,
       CAST(coalesce(s.fingerprint, '') AS TEXT) AS subtitles_fingerprint,
       CAST(coalesce(s.sidecars, '') AS TEXT) AS subtitles_sidecars,
       CAST(coalesce(t.fingerprint, '') AS TEXT) AS trickplay_fingerprint,
       CAST(coalesce(g.fingerprint, '') AS TEXT) AS segments_fingerprint,
       CAST(coalesce(g.audio, 0) AS INTEGER) AS segments_audio
FROM media_files f
LEFT JOIN subtitle_sets s ON s.file_id = f.id
LEFT JOIN trickplay t ON t.file_id = f.id
LEFT JOIN segment_scans g ON g.file_id = f.id
WHERE f.library_id = ?
`

type ListLibraryFilesRow struct {
	ID                   domain.ID
	Path                 string
	Size                 int64
	Mtime                int64
	Fingerprint          string
	MissingSince         sql.NullInt64
	AnalyzedAt           sql.NullInt64
	SubtitlesFingerprint string
	SubtitlesSidecars    string
	TrickplayFingerprint string
	SegmentsFingerprint  string
	SegmentsAudio        int64
}

func (q *Queries) ListLibraryFiles(ctx context.Context, libraryID domain.ID) ([]ListLibraryFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLibraryFiles, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLibraryFilesRow{}
	for rows.Next() {
		var i ListLibraryFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Size,
			&i.Mtime,
			&i.Fingerprint,
			&i.MissingSince,
			&i.AnalyzedAt,
			&i.SubtitlesFingerprint,
			&i.SubtitlesSidecars,
			&i.TrickplayFingerprint,
			&i.SegmentsFingerprint,
			&i.SegmentsAudio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresentFileItems = `-- name: ListPresentFileItems :many
SELECT f.path, i.id AS item_id, i.kind, e.season_id, e.series_id, t.album_id, t.artist_id
FROM media_files f
JOIN item_files l ON l.file_id = f.id
JOIN items i ON i.id = l.item_id
LEFT JOIN episodes e ON e.item_id = i.id
LEFT JOIN tracks t ON t.item_id = i.id
WHERE f.library_id = ? AND f.missing_since IS NULL
`

type ListPresentFileItemsRow struct {
	Path     string
	ItemID   domain.ID
	Kind     string
	SeasonID *domain.ID
	SeriesID *domain.ID
	AlbumID  *domain.ID
	ArtistID *domain.ID
}

func (q *Queries) ListPresentFileItems(ctx context.Context, libraryID domain.ID) ([]ListPresentFileItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPresentFileItems, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPresentFileItemsRow{}
	for rows.Next() {
		var i ListPresentFileItemsRow
		if err := rows.Scan(
			&i.Path,
			&i.ItemID,
			&i.Kind,
			&i.SeasonID,
			&i.SeriesID,
			&i.AlbumID,
			&i.ArtistID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrickplayKeys = `-- name: ListTrickplayKeys :many
SELECT file_id, key FROM trickplay WHERE key <> ''
`

type ListTrickplayKeysRow struct {
	FileID domain.ID
	Key    string
}

func (q *Queries) ListTrickplayKeys(ctx context.Context) ([]ListTrickplayKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listTrickplayKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrickplayKeysRow{}
	for rows.Next() {
		var i ListTrickplayKeysRow
		if err := rows.Scan(&i.FileID, &i.Key); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFileMissing = `-- name: MarkFileMissing :exec
UPDATE media_files SET missing_since = ?, updated_at = ? WHERE id = ? AND missing_since IS NULL
`

type MarkFileMissingParams struct {
	MissingSince sql.NullInt64
	UpdatedAt    int64
	ID           domain.ID
}

func (q *Queries) MarkFileMissing(ctx context.Context, arg MarkFileMissingParams) error {
	_, err := q.db.ExecContext(ctx, markFileMissing, arg.MissingSince, arg.UpdatedAt, arg.ID)
	return err
}

const markFilePresent = `-- name: MarkFilePresent :exec
UPDATE media_files SET missing_since = NULL, updated_at = ? WHERE id = ? AND missing_since IS NOT NULL
`

type MarkFilePresentParams struct {
	UpdatedAt int64
	ID        domain.ID
}

func (q *Queries) MarkFilePresent(ctx context.Context, arg MarkFilePresentParams) error {
	_, err := q.db.ExecContext(ctx, markFilePresent, arg.UpdatedAt, arg.ID)
	return err
}

const moveFile = `-- name: MoveFile :exec
UPDATE media_files SET path = ?, missing_since = NULL, updated_at = ? WHERE id = ?
`

type MoveFileParams struct {
	Path      string
	UpdatedAt int64
	ID        domain.ID
}

func (q *Queries) MoveFile(ctx context.Context, arg MoveFileParams) error {
	_, err := q.db.ExecContext(ctx, moveFile, arg.Path, arg.UpdatedAt, arg.ID)
	return err
}

const setFileAnalysis = `-- name: SetFileAnalysis :exec
UPDATE media_files
SET container = ?, duration_ms = ?, bitrate = ?, tags = ?, analyzed_at = ?, analysis_error = '', updated_at = ?
WHERE id = ?
`

type SetFileAnalysisParams struct {
	Container  string
	DurationMs int64
	Bitrate    int64
	Tags       string
	AnalyzedAt sql.NullInt64
	UpdatedAt  int64
	ID         domain.ID
}

func (q *Queries) SetFileAnalysis(ctx context.Context, arg SetFileAnalysisParams) error {
	_, err := q.db.ExecContext(ctx, setFileAnalysis,
		arg.Container,
		arg.DurationMs,
		arg.Bitrate,
		arg.Tags,
		arg.AnalyzedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setFileAnalysisError = `-- name: SetFileAnalysisError :exec
UPDATE media_files SET analysis_error = ?, updated_at = ? WHERE id = ?
`

type SetFileAnalysisErrorParams struct {
	AnalysisError string
	UpdatedAt     int64
	ID            domain.ID
}

func (q *Queries) SetFileAnalysisError(ctx context.Context, arg SetFileAnalysisErrorParams) error {
	_, err := q.db.ExecContext(ctx, setFileAnalysisError, arg.AnalysisError, arg.UpdatedAt, arg.ID)
	return err
}

const updateFileContent = `-- name: UpdateFileContent :exec
UPDATE media_files
SET size = ?, mtime = ?, fingerprint = ?, missing_since = NULL, analyzed_at = NULL, updated_at = ?
WHERE id = ?
`

type UpdateFileContentParams struct {
	Size        int64
	Mtime       int64
	Fingerprint string
	UpdatedAt   int64
	ID          domain.ID
}

func (q *Queries) UpdateFileContent(ctx context.Context, arg UpdateFileContentParams) error {
	_, err := q.db.ExecContext(ctx, updateFileContent,
		arg.Size,
		arg.Mtime,
		arg.Fingerprint,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertTrickplay = `-- name: UpsertTrickplay :exec
INSERT INTO trickplay (file_id, fingerprint, key, interval_ms, width, height, columns, rows, count, sheets, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (file_id) DO UPDATE SET fingerprint = excluded.fingerprint, key = excluded.key,
    interval_ms = excluded.interval_ms, width = excluded.width, height = excluded.height,
    columns = excluded.columns, rows = excluded.rows, count = excluded.count, sheets = excluded.sheets,
    created_at = excluded.created_at
`

type UpsertTrickplayParams struct {
	FileID      domain.ID
	Fingerprint string
	Key         string
	IntervalMs  int64
	Width       int64
	Height      int64
	Columns     int64
	Rows        int64
	Count       int64
	Sheets      int64
	CreatedAt   int64
}

func (q *Queries) UpsertTrickplay(ctx context.Context, arg UpsertTrickplayParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrickplay,
		arg.FileID,
		arg.Fingerprint,
		arg.Key,
		arg.IntervalMs,
		arg.Width,
		arg.Height,
		arg.Columns,
		arg.Rows,
		arg.Count,
		arg.Sheets,
		arg.CreatedAt,
	)
	return err
}
