// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package sqlc

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT count(*) FROM settings
`

func (q *Queries) Ping(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, ping)
	var count int64
	err := row.Scan(&count)
	return count, err
}
