// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"

	"github.com/laterna-project/laterna/internal/domain"
)

const deletePlay = `-- name: DeletePlay :execrows
DELETE FROM play_history WHERE id = ? AND profile_id = ?
`

type DeletePlayParams struct {
	ID        domain.ID
	ProfileID domain.ID
}

func (q *Queries) DeletePlay(ctx context.Context, arg DeletePlayParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePlay, arg.ID, arg.ProfileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProfilePlays = `-- name: DeleteProfilePlays :execrows
DELETE FROM play_history WHERE profile_id = ?
`

func (q *Queries) DeleteProfilePlays(ctx context.Context, profileID domain.ID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProfilePlays, profileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const firstPlay = `-- name: FirstPlay :one
SELECT id, profile_id, item_id, kind, series_id, album_id, artist_id, title, subtitle, started_at, ended_at, watched_ms, position_ms, duration_ms, completed, device, offline, import_key FROM play_history
WHERE profile_id = ?1 AND started_at >= ?2 AND started_at < ?3
ORDER BY started_at, id
LIMIT 1
`

type FirstPlayParams struct {
	ProfileID domain.ID
	FromAt    int64
	ToAt      int64
}

func (q *Queries) FirstPlay(ctx context.Context, arg FirstPlayParams) (PlayHistory, error) {
	row := q.db.QueryRowContext(ctx, firstPlay, arg.ProfileID, arg.FromAt, arg.ToAt)
	var i PlayHistory
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.ItemID,
		&i.Kind,
		&i.SeriesID,
		&i.AlbumID,
		&i.ArtistID,
		&i.Title,
		&i.Subtitle,
		&i.StartedAt,
		&i.EndedAt,
		&i.WatchedMs,
		&i.PositionMs,
		&i.DurationMs,
		&i.Completed,
		&i.Device,
		&i.Offline,
		&i.ImportKey,
	)
	return i, err
}

const insertImportedPlay = `-- name: InsertImportedPlay :execrows
INSERT INTO play_history (id, profile_id, item_id, kind, series_id, album_id, artist_id, title, subtitle, started_at, ended_at,
                          watched_ms, position_ms, duration_ms, completed, device, offline, import_key)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (profile_id, import_key) WHERE import_key IS NOT NULL DO NOTHING
`

type InsertImportedPlayParams struct {
	ID         domain.ID
	ProfileID  domain.ID
	ItemID     *domain.ID
	Kind       string
	SeriesID   *domain.ID
	AlbumID    *domain.ID
	ArtistID   *domain.ID
	Title      string
	Subtitle   string
	StartedAt  int64
	EndedAt    int64
	WatchedMs  int64
	PositionMs int64
	DurationMs int64
	Completed  int64
	Device     string
	Offline    int64
	ImportKey  sql.NullString
}

func (q *Queries) InsertImportedPlay(ctx context.Context, arg InsertImportedPlayParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertImportedPlay,
		arg.ID,
		arg.ProfileID,
		arg.ItemID,
		arg.Kind,
		arg.SeriesID,
		arg.AlbumID,
		arg.ArtistID,
		arg.Title,
		arg.Subtitle,
		arg.StartedAt,
		arg.EndedAt,
		arg.WatchedMs,
		arg.PositionMs,
		arg.DurationMs,
		arg.Completed,
		arg.Device,
		arg.Offline,
		arg.ImportKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertPlay = `-- name: InsertPlay :exec
INSERT INTO play_history (id, profile_id, item_id, kind, series_id, album_id, artist_id, title, subtitle, started_at, ended_at,
                          watched_ms, position_ms, duration_ms, completed, device, offline)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPlayParams struct {
	ID         domain.ID
	ProfileID  domain.ID
	ItemID     *domain.ID
	Kind       string
	SeriesID   *domain.ID
	AlbumID    *domain.ID
	ArtistID   *domain.ID
	Title      string
	Subtitle   string
	StartedAt  int64
	EndedAt    int64
	WatchedMs  int64
	PositionMs int64
	DurationMs int64
	Completed  int64
	Device     string
	Offline    int64
}

func (q *Queries) InsertPlay(ctx context.Context, arg InsertPlayParams) error {
	_, err := q.db.ExecContext(ctx, insertPlay,
		arg.ID,
		arg.ProfileID,
		arg.ItemID,
		arg.Kind,
		arg.SeriesID,
		arg.AlbumID,
		arg.ArtistID,
		arg.Title,
		arg.Subtitle,
		arg.StartedAt,
		arg.EndedAt,
		arg.WatchedMs,
		arg.PositionMs,
		arg.DurationMs,
		arg.Completed,
		arg.Device,
		arg.Offline,
	)
	return err
}

const lastPlay = `-- name: LastPlay :one
SELECT id, profile_id, item_id, kind, series_id, album_id, artist_id, title, subtitle, started_at, ended_at, watched_ms, position_ms, duration_ms, completed, device, offline, import_key FROM play_history
WHERE profile_id = ?1 AND started_at >= ?2 AND started_at < ?3
ORDER BY started_at DESC, id DESC
LIMIT 1
`

type LastPlayParams struct {
	ProfileID domain.ID
	FromAt    int64
	ToAt      int64
}

func (q *Queries) LastPlay(ctx context.Context, arg LastPlayParams) (PlayHistory, error) {
	row := q.db.QueryRowContext(ctx, lastPlay, arg.ProfileID, arg.FromAt, arg.ToAt)
	var i PlayHistory
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.ItemID,
		&i.Kind,
		&i.SeriesID,
		&i.AlbumID,
		&i.ArtistID,
		&i.Title,
		&i.Subtitle,
		&i.StartedAt,
		&i.EndedAt,
		&i.WatchedMs,
		&i.PositionMs,
		&i.DurationMs,
		&i.Completed,
		&i.Device,
		&i.Offline,
		&i.ImportKey,
	)
	return i, err
}

const listGenresOfItems = `-- name: ListGenresOfItems :many
SELECT item_id, genre FROM item_genres WHERE item_id IN (/*SLICE:item_ids*/?) ORDER BY item_id, genre
`

func (q *Queries) ListGenresOfItems(ctx context.Context, itemIds []domain.ID) ([]ItemGenre, error) {
	query := listGenresOfItems
	var queryParams []interface{}
	if len(itemIds) > 0 {
		for _, v := range itemIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:item_ids*/?", strings.Repeat(",?", len(itemIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:item_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemGenre{}
	for rows.Next() {
		var i ItemGenre
		if err := rows.Scan(&i.ItemID, &i.Genre); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlays = `-- name: ListPlays :many
SELECT id, profile_id, item_id, kind, series_id, album_id, artist_id, title, subtitle, started_at, ended_at, watched_ms, position_ms, duration_ms, completed, device, offline, import_key FROM play_history
WHERE profile_id = ?1
  AND (started_at < ?2 OR (started_at = ?2 AND id < ?3))
ORDER BY started_at DESC, id DESC
LIMIT ?4
`

type ListPlaysParams struct {
	ProfileID domain.ID
	BeforeAt  int64
	BeforeID  domain.ID
	Lim       int64
}

func (q *Queries) ListPlays(ctx context.Context, arg ListPlaysParams) ([]PlayHistory, error) {
	rows, err := q.db.QueryContext(ctx, listPlays,
		arg.ProfileID,
		arg.BeforeAt,
		arg.BeforeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlayHistory{}
	for rows.Next() {
		var i PlayHistory
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.ItemID,
			&i.Kind,
			&i.SeriesID,
			&i.AlbumID,
			&i.ArtistID,
			&i.Title,
			&i.Subtitle,
			&i.StartedAt,
			&i.EndedAt,
			&i.WatchedMs,
			&i.PositionMs,
			&i.DurationMs,
			&i.Completed,
			&i.Device,
			&i.Offline,
			&i.ImportKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
