// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/laterna-project/laterna/internal/domain"
)

const countPresentItemsByKind = `-- name: CountPresentItemsByKind :many
SELECT kind, count(*) AS n FROM items WHERE present = 1 GROUP BY kind ORDER BY kind
`

type CountPresentItemsByKindRow struct {
	Kind string
	N    int64
}

func (q *Queries) CountPresentItemsByKind(ctx context.Context) ([]CountPresentItemsByKindRow, error) {
	rows, err := q.db.QueryContext(ctx, countPresentItemsByKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountPresentItemsByKindRow{}
	for rows.Next() {
		var i CountPresentItemsByKindRow
		if err := rows.Scan(&i.Kind, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteEmptyAlbums = `-- name: DeleteEmptyAlbums :execrows
DELETE FROM items
WHERE library_id = ? AND kind = 'album'
  AND NOT EXISTS (SELECT 1 FROM tracks t WHERE t.album_id = items.id)
`

func (q *Queries) DeleteEmptyAlbums(ctx context.Context, libraryID domain.ID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEmptyAlbums, libraryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEmptyArtists = `-- name: DeleteEmptyArtists :execrows
DELETE FROM items
WHERE items.library_id = ? AND items.kind = 'artist'
  AND NOT EXISTS (SELECT 1 FROM items a WHERE a.parent_id = items.id)
`

func (q *Queries) DeleteEmptyArtists(ctx context.Context, libraryID domain.ID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEmptyArtists, libraryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEmptySeasons = `-- name: DeleteEmptySeasons :execrows
DELETE FROM items
WHERE library_id = ? AND kind = 'season'
  AND NOT EXISTS (SELECT 1 FROM episodes e WHERE e.season_id = items.id)
`

func (q *Queries) DeleteEmptySeasons(ctx context.Context, libraryID domain.ID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEmptySeasons, libraryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEmptySeries = `-- name: DeleteEmptySeries :execrows
DELETE FROM items
WHERE library_id = ? AND kind = 'series'
  AND NOT EXISTS (SELECT 1 FROM seasons s WHERE s.series_id = items.id)
`

func (q *Queries) DeleteEmptySeries(ctx context.Context, libraryID domain.ID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEmptySeries, libraryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images WHERE id = ?
`

func (q *Queries) DeleteImage(ctx context.Context, id domain.ID) error {
	_, err := q.db.ExecContext(ctx, deleteImage, id)
	return err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM items WHERE id = ?
`

func (q *Queries) DeleteItem(ctx context.Context, id domain.ID) error {
	_, err := q.db.ExecContext(ctx, deleteItem, id)
	return err
}

const deleteItemGenres = `-- name: DeleteItemGenres :exec
DELETE FROM item_genres WHERE item_id = ?
`

func (q *Queries) DeleteItemGenres(ctx context.Context, itemID domain.ID) error {
	_, err := q.db.ExecContext(ctx, deleteItemGenres, itemID)
	return err
}

const deleteItemPeople = `-- name: DeleteItemPeople :exec
DELETE FROM item_people WHERE item_id = ?
`

func (q *Queries) DeleteItemPeople(ctx context.Context, itemID domain.ID) error {
	_, err := q.db.ExecContext(ctx, deleteItemPeople, itemID)
	return err
}

const deleteItemStudios = `-- name: DeleteItemStudios :exec
DELETE FROM item_studios WHERE item_id = ?
`

func (q *Queries) DeleteItemStudios(ctx context.Context, itemID domain.ID) error {
	_, err := q.db.ExecContext(ctx, deleteItemStudios, itemID)
	return err
}

const deleteOrphanLeafItems = `-- name: DeleteOrphanLeafItems :execrows
DELETE FROM items
WHERE library_id = ? AND kind IN ('movie', 'episode', 'track', 'book', 'photo')
  AND NOT EXISTS (SELECT 1 FROM item_files l WHERE l.item_id = items.id)
`

func (q *Queries) DeleteOrphanLeafItems(ctx context.Context, libraryID domain.ID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOrphanLeafItems, libraryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOrphanPeople = `-- name: DeleteOrphanPeople :execrows
DELETE FROM people WHERE NOT EXISTS (SELECT 1 FROM item_people ip WHERE ip.person_id = people.id)
`

func (q *Queries) DeleteOrphanPeople(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOrphanPeople)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProviderIDs = `-- name: DeleteProviderIDs :exec
DELETE FROM provider_ids WHERE item_id = ?
`

func (q *Queries) DeleteProviderIDs(ctx context.Context, itemID domain.ID) error {
	_, err := q.db.ExecContext(ctx, deleteProviderIDs, itemID)
	return err
}

const firstFileOfSeason = `-- name: FirstFileOfSeason :one
SELECT f.path
FROM media_files f
JOIN item_files l ON l.file_id = f.id
JOIN episodes e ON e.item_id = l.item_id
WHERE e.season_id = ? AND f.missing_since IS NULL
ORDER BY e.number
LIMIT 1
`

func (q *Queries) FirstFileOfSeason(ctx context.Context, seasonID domain.ID) (string, error) {
	row := q.db.QueryRowContext(ctx, firstFileOfSeason, seasonID)
	var path string
	err := row.Scan(&path)
	return path, err
}

const firstFileOfSeries = `-- name: FirstFileOfSeries :one
SELECT f.path
FROM media_files f
JOIN item_files l ON l.file_id = f.id
JOIN episodes e ON e.item_id = l.item_id
WHERE e.series_id = ? AND f.missing_since IS NULL
ORDER BY e.season_number, e.number
LIMIT 1
`

func (q *Queries) FirstFileOfSeries(ctx context.Context, seriesID domain.ID) (string, error) {
	row := q.db.QueryRowContext(ctx, firstFileOfSeries, seriesID)
	var path string
	err := row.Scan(&path)
	return path, err
}

const getEpisode = `-- name: GetEpisode :one
SELECT item_id, series_id, season_id, season_number, number, number_end, absolute FROM episodes WHERE item_id = ?
`

func (q *Queries) GetEpisode(ctx context.Context, itemID domain.ID) (Episode, error) {
	row := q.db.QueryRowContext(ctx, getEpisode, itemID)
	var i Episode
	err := row.Scan(
		&i.ItemID,
		&i.SeriesID,
		&i.SeasonID,
		&i.SeasonNumber,
		&i.Number,
		&i.NumberEnd,
		&i.Absolute,
	)
	return i, err
}

const getFileItem = `-- name: GetFileItem :one
SELECT item_id FROM item_files WHERE file_id = ?
`

func (q *Queries) GetFileItem(ctx context.Context, fileID domain.ID) (domain.ID, error) {
	row := q.db.QueryRowContext(ctx, getFileItem, fileID)
	var item_id domain.ID
	err := row.Scan(&item_id)
	return item_id, err
}

const getImage = `-- name: GetImage :one
SELECT id, item_id, person_id, theme_id, kind, source, path, remote_url, width, height, blurhash, hash, updated_at FROM images WHERE id = ?
`

func (q *Queries) GetImage(ctx context.Context, id domain.ID) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImage, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.PersonID,
		&i.ThemeID,
		&i.Kind,
		&i.Source,
		&i.Path,
		&i.RemoteUrl,
		&i.Width,
		&i.Height,
		&i.Blurhash,
		&i.Hash,
		&i.UpdatedAt,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id, library_id, kind, parent_id, group_key, title, sort_title, original_title, year, premiere_date, overview, tagline, official_rating, community_rating, runtime_ms, metadata_at, added_at, updated_at, age_rating, present FROM items WHERE id = ?
`

func (q *Queries) GetItem(ctx context.Context, id domain.ID) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Kind,
		&i.ParentID,
		&i.GroupKey,
		&i.Title,
		&i.SortTitle,
		&i.OriginalTitle,
		&i.Year,
		&i.PremiereDate,
		&i.Overview,
		&i.Tagline,
		&i.OfficialRating,
		&i.CommunityRating,
		&i.RuntimeMs,
		&i.MetadataAt,
		&i.AddedAt,
		&i.UpdatedAt,
		&i.AgeRating,
		&i.Present,
	)
	return i, err
}

const getItemByGroupKey = `-- name: GetItemByGroupKey :one
SELECT id, library_id, kind, parent_id, group_key, title, sort_title, original_title, year, premiere_date, overview, tagline, official_rating, community_rating, runtime_ms, metadata_at, added_at, updated_at, age_rating, present FROM items WHERE library_id = ? AND group_key = ?
`

type GetItemByGroupKeyParams struct {
	LibraryID domain.ID
	GroupKey  string
}

func (q *Queries) GetItemByGroupKey(ctx context.Context, arg GetItemByGroupKeyParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemByGroupKey, arg.LibraryID, arg.GroupKey)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Kind,
		&i.ParentID,
		&i.GroupKey,
		&i.Title,
		&i.SortTitle,
		&i.OriginalTitle,
		&i.Year,
		&i.PremiereDate,
		&i.Overview,
		&i.Tagline,
		&i.OfficialRating,
		&i.CommunityRating,
		&i.RuntimeMs,
		&i.MetadataAt,
		&i.AddedAt,
		&i.UpdatedAt,
		&i.AgeRating,
		&i.Present,
	)
	return i, err
}

const getItemImage = `-- name: GetItemImage :one
SELECT id, item_id, person_id, theme_id, kind, source, path, remote_url, width, height, blurhash, hash, updated_at FROM images WHERE item_id = ? AND kind = ?
`

type GetItemImageParams struct {
	ItemID *domain.ID
	Kind   string
}

func (q *Queries) GetItemImage(ctx context.Context, arg GetItemImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, getItemImage, arg.ItemID, arg.Kind)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.PersonID,
		&i.ThemeID,
		&i.Kind,
		&i.Source,
		&i.Path,
		&i.RemoteUrl,
		&i.Width,
		&i.Height,
		&i.Blurhash,
		&i.Hash,
		&i.UpdatedAt,
	)
	return i, err
}

const getPersonByKey = `-- name: GetPersonByKey :one
SELECT id, name, name_key, created_at FROM people WHERE name_key = ?
`

func (q *Queries) GetPersonByKey(ctx context.Context, nameKey string) (Person, error) {
	row := q.db.QueryRowContext(ctx, getPersonByKey, nameKey)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameKey,
		&i.CreatedAt,
	)
	return i, err
}

const getPersonImage = `-- name: GetPersonImage :one
SELECT id, item_id, person_id, theme_id, kind, source, path, remote_url, width, height, blurhash, hash, updated_at FROM images WHERE person_id = ? AND kind = ?
`

type GetPersonImageParams struct {
	PersonID *domain.ID
	Kind     string
}

func (q *Queries) GetPersonImage(ctx context.Context, arg GetPersonImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, getPersonImage, arg.PersonID, arg.Kind)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.PersonID,
		&i.ThemeID,
		&i.Kind,
		&i.Source,
		&i.Path,
		&i.RemoteUrl,
		&i.Width,
		&i.Height,
		&i.Blurhash,
		&i.Hash,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeason = `-- name: GetSeason :one
SELECT item_id, series_id, number FROM seasons WHERE item_id = ?
`

func (q *Queries) GetSeason(ctx context.Context, itemID domain.ID) (Season, error) {
	row := q.db.QueryRowContext(ctx, getSeason, itemID)
	var i Season
	err := row.Scan(&i.ItemID, &i.SeriesID, &i.Number)
	return i, err
}

const insertEpisode = `-- name: InsertEpisode :exec
INSERT INTO episodes (item_id, series_id, season_id, season_number, number, number_end, absolute)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertEpisodeParams struct {
	ItemID       domain.ID
	SeriesID     domain.ID
	SeasonID     domain.ID
	SeasonNumber int64
	Number       int64
	NumberEnd    int64
	Absolute     int64
}

func (q *Queries) InsertEpisode(ctx context.Context, arg InsertEpisodeParams) error {
	_, err := q.db.ExecContext(ctx, insertEpisode,
		arg.ItemID,
		arg.SeriesID,
		arg.SeasonID,
		arg.SeasonNumber,
		arg.Number,
		arg.NumberEnd,
		arg.Absolute,
	)
	return err
}

const insertImage = `-- name: InsertImage :exec
INSERT INTO images (id, item_id, person_id, kind, source, path, remote_url, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertImageParams struct {
	ID        domain.ID
	ItemID    *domain.ID
	PersonID  *domain.ID
	Kind      string
	Source    string
	Path      string
	RemoteUrl string
	UpdatedAt int64
}

func (q *Queries) InsertImage(ctx context.Context, arg InsertImageParams) error {
	_, err := q.db.ExecContext(ctx, insertImage,
		arg.ID,
		arg.ItemID,
		arg.PersonID,
		arg.Kind,
		arg.Source,
		arg.Path,
		arg.RemoteUrl,
		arg.UpdatedAt,
	)
	return err
}

const insertItem = `-- name: InsertItem :exec
INSERT INTO items (id, library_id, kind, parent_id, group_key, title, sort_title, year, added_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertItemParams struct {
	ID        domain.ID
	LibraryID domain.ID
	Kind      string
	ParentID  *domain.ID
	GroupKey  string
	Title     string
	SortTitle string
	Year      int64
	AddedAt   int64
	UpdatedAt int64
}

func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) error {
	_, err := q.db.ExecContext(ctx, insertItem,
		arg.ID,
		arg.LibraryID,
		arg.Kind,
		arg.ParentID,
		arg.GroupKey,
		arg.Title,
		arg.SortTitle,
		arg.Year,
		arg.AddedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertItemGenre = `-- name: InsertItemGenre :exec
INSERT INTO item_genres (item_id, genre) VALUES (?, ?) ON CONFLICT DO NOTHING
`

type InsertItemGenreParams struct {
	ItemID domain.ID
	Genre  string
}

func (q *Queries) InsertItemGenre(ctx context.Context, arg InsertItemGenreParams) error {
	_, err := q.db.ExecContext(ctx, insertItemGenre, arg.ItemID, arg.Genre)
	return err
}

const insertItemPerson = `-- name: InsertItemPerson :exec
INSERT INTO item_people (item_id, person_id, role, character, sort_order) VALUES (?, ?, ?, ?, ?)
ON CONFLICT DO NOTHING
`

type InsertItemPersonParams struct {
	ItemID    domain.ID
	PersonID  domain.ID
	Role      string
	Character string
	SortOrder int64
}

func (q *Queries) InsertItemPerson(ctx context.Context, arg InsertItemPersonParams) error {
	_, err := q.db.ExecContext(ctx, insertItemPerson,
		arg.ItemID,
		arg.PersonID,
		arg.Role,
		arg.Character,
		arg.SortOrder,
	)
	return err
}

const insertItemStudio = `-- name: InsertItemStudio :exec
INSERT INTO item_studios (item_id, studio) VALUES (?, ?) ON CONFLICT DO NOTHING
`

type InsertItemStudioParams struct {
	ItemID domain.ID
	Studio string
}

func (q *Queries) InsertItemStudio(ctx context.Context, arg InsertItemStudioParams) error {
	_, err := q.db.ExecContext(ctx, insertItemStudio, arg.ItemID, arg.Studio)
	return err
}

const insertPerson = `-- name: InsertPerson :exec
INSERT INTO people (id, name, name_key, created_at) VALUES (?, ?, ?, ?)
`

type InsertPersonParams struct {
	ID        domain.ID
	Name      string
	NameKey   string
	CreatedAt int64
}

func (q *Queries) InsertPerson(ctx context.Context, arg InsertPersonParams) error {
	_, err := q.db.ExecContext(ctx, insertPerson,
		arg.ID,
		arg.Name,
		arg.NameKey,
		arg.CreatedAt,
	)
	return err
}

const insertProviderID = `-- name: InsertProviderID :exec
INSERT INTO provider_ids (item_id, provider, value) VALUES (?, ?, ?)
`

type InsertProviderIDParams struct {
	ItemID   domain.ID
	Provider string
	Value    string
}

func (q *Queries) InsertProviderID(ctx context.Context, arg InsertProviderIDParams) error {
	_, err := q.db.ExecContext(ctx, insertProviderID, arg.ItemID, arg.Provider, arg.Value)
	return err
}

const insertSeason = `-- name: InsertSeason :exec
INSERT INTO seasons (item_id, series_id, number) VALUES (?, ?, ?)
`

type InsertSeasonParams struct {
	ItemID   domain.ID
	SeriesID domain.ID
	Number   int64
}

func (q *Queries) InsertSeason(ctx context.Context, arg InsertSeasonParams) error {
	_, err := q.db.ExecContext(ctx, insertSeason, arg.ItemID, arg.SeriesID, arg.Number)
	return err
}

const linkFile = `-- name: LinkFile :exec
INSERT INTO item_files (item_id, file_id, version, part) VALUES (?, ?, ?, ?)
ON CONFLICT (file_id) DO UPDATE SET item_id = excluded.item_id, version = excluded.version, part = excluded.part
`

type LinkFileParams struct {
	ItemID  domain.ID
	FileID  domain.ID
	Version string
	Part    int64
}

func (q *Queries) LinkFile(ctx context.Context, arg LinkFileParams) error {
	_, err := q.db.ExecContext(ctx, linkFile,
		arg.ItemID,
		arg.FileID,
		arg.Version,
		arg.Part,
	)
	return err
}

const listItemFiles = `-- name: ListItemFiles :many
SELECT f.id, f.library_id, f.path, f.size, f.mtime, f.fingerprint, f.missing_since, f.analyzed_at, f.analysis_error, f.container, f.duration_ms, f.bitrate, f.created_at, f.updated_at, f.tags, l.version, l.part
FROM item_files l JOIN media_files f ON f.id = l.file_id
WHERE l.item_id = ?
ORDER BY l.version, l.part, f.path
`

type ListItemFilesRow struct {
	ID            domain.ID
	LibraryID     domain.ID
	Path          string
	Size          int64
	Mtime         int64
	Fingerprint   string
	MissingSince  sql.NullInt64
	AnalyzedAt    sql.NullInt64
	AnalysisError string
	Container     string
	DurationMs    int64
	Bitrate       int64
	CreatedAt     int64
	UpdatedAt     int64
	Tags          string
	Version       string
	Part          int64
}

func (q *Queries) ListItemFiles(ctx context.Context, itemID domain.ID) ([]ListItemFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemFiles, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemFilesRow{}
	for rows.Next() {
		var i ListItemFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Path,
			&i.Size,
			&i.Mtime,
			&i.Fingerprint,
			&i.MissingSince,
			&i.AnalyzedAt,
			&i.AnalysisError,
			&i.Container,
			&i.DurationMs,
			&i.Bitrate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tags,
			&i.Version,
			&i.Part,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemGenres = `-- name: ListItemGenres :many
SELECT genre FROM item_genres WHERE item_id = ? ORDER BY genre
`

func (q *Queries) ListItemGenres(ctx context.Context, itemID domain.ID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listItemGenres, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var genre string
		if err := rows.Scan(&genre); err != nil {
			return nil, err
		}
		items = append(items, genre)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemImages = `-- name: ListItemImages :many
SELECT id, item_id, person_id, theme_id, kind, source, path, remote_url, width, height, blurhash, hash, updated_at FROM images WHERE item_id = ? ORDER BY kind
`

func (q *Queries) ListItemImages(ctx context.Context, itemID *domain.ID) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listItemImages, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.PersonID,
			&i.ThemeID,
			&i.Kind,
			&i.Source,
			&i.Path,
			&i.RemoteUrl,
			&i.Width,
			&i.Height,
			&i.Blurhash,
			&i.Hash,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemPeople = `-- name: ListItemPeople :many
SELECT p.id, p.name, ip.role, ip.character, ip.sort_order,
       pi.id AS image_id,
       CAST(coalesce(pi.width, 0) AS INTEGER) AS image_width,
       CAST(coalesce(pi.height, 0) AS INTEGER) AS image_height,
       CAST(coalesce(pi.blurhash, '') AS TEXT) AS image_blurhash,
       CAST(coalesce(pi.hash, '') AS TEXT) AS image_hash
FROM item_people ip
JOIN people p ON p.id = ip.person_id
LEFT JOIN images pi ON pi.person_id = p.id AND pi.kind = 'poster' AND pi.hash <> ''
WHERE ip.item_id = ?
ORDER BY ip.role, ip.sort_order, p.name_key
`

type ListItemPeopleRow struct {
	ID            domain.ID
	Name          string
	Role          string
	Character     string
	SortOrder     int64
	ImageID       *domain.ID
	ImageWidth    int64
	ImageHeight   int64
	ImageBlurhash string
	ImageHash     string
}

func (q *Queries) ListItemPeople(ctx context.Context, itemID domain.ID) ([]ListItemPeopleRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemPeople, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemPeopleRow{}
	for rows.Next() {
		var i ListItemPeopleRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Character,
			&i.SortOrder,
			&i.ImageID,
			&i.ImageWidth,
			&i.ImageHeight,
			&i.ImageBlurhash,
			&i.ImageHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemStudios = `-- name: ListItemStudios :many
SELECT studio FROM item_studios WHERE item_id = ? ORDER BY studio
`

func (q *Queries) ListItemStudios(ctx context.Context, itemID domain.ID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listItemStudios, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var studio string
		if err := rows.Scan(&studio); err != nil {
			return nil, err
		}
		items = append(items, studio)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderIDs = `-- name: ListProviderIDs :many
SELECT provider, value FROM provider_ids WHERE item_id = ? ORDER BY provider
`

type ListProviderIDsRow struct {
	Provider string
	Value    string
}

func (q *Queries) ListProviderIDs(ctx context.Context, itemID domain.ID) ([]ListProviderIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProviderIDs, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProviderIDsRow{}
	for rows.Next() {
		var i ListProviderIDsRow
		if err := rows.Scan(&i.Provider, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemoteImagePaths = `-- name: ListRemoteImagePaths :many
SELECT path FROM images WHERE source IN ('remote', 'embedded')
`

func (q *Queries) ListRemoteImagePaths(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRemoteImagePaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceImageFile = `-- name: ReplaceImageFile :exec
UPDATE images
SET source = ?, path = ?, remote_url = ?, width = 0, height = 0, blurhash = '', hash = '', updated_at = ?
WHERE id = ?
`

type ReplaceImageFileParams struct {
	Source    string
	Path      string
	RemoteUrl string
	UpdatedAt int64
	ID        domain.ID
}

func (q *Queries) ReplaceImageFile(ctx context.Context, arg ReplaceImageFileParams) error {
	_, err := q.db.ExecContext(ctx, replaceImageFile,
		arg.Source,
		arg.Path,
		arg.RemoteUrl,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setImageAnalysis = `-- name: SetImageAnalysis :exec
UPDATE images SET width = ?, height = ?, blurhash = ?, hash = ?, updated_at = ? WHERE id = ?
`

type SetImageAnalysisParams struct {
	Width     int64
	Height    int64
	Blurhash  string
	Hash      string
	UpdatedAt int64
	ID        domain.ID
}

func (q *Queries) SetImageAnalysis(ctx context.Context, arg SetImageAnalysisParams) error {
	_, err := q.db.ExecContext(ctx, setImageAnalysis,
		arg.Width,
		arg.Height,
		arg.Blurhash,
		arg.Hash,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setItemGroupKey = `-- name: SetItemGroupKey :exec
UPDATE items SET group_key = ?, updated_at = ? WHERE id = ?
`

type SetItemGroupKeyParams struct {
	GroupKey  string
	UpdatedAt int64
	ID        domain.ID
}

func (q *Queries) SetItemGroupKey(ctx context.Context, arg SetItemGroupKeyParams) error {
	_, err := q.db.ExecContext(ctx, setItemGroupKey, arg.GroupKey, arg.UpdatedAt, arg.ID)
	return err
}

const setItemParent = `-- name: SetItemParent :exec
UPDATE items SET parent_id = ?, updated_at = ? WHERE id = ?
`

type SetItemParentParams struct {
	ParentID  *domain.ID
	UpdatedAt int64
	ID        domain.ID
}

func (q *Queries) SetItemParent(ctx context.Context, arg SetItemParentParams) error {
	_, err := q.db.ExecContext(ctx, setItemParent, arg.ParentID, arg.UpdatedAt, arg.ID)
	return err
}

const updateItemMetadata = `-- name: UpdateItemMetadata :exec
UPDATE items
SET title = ?, sort_title = ?, original_title = ?, year = ?, premiere_date = ?, overview = ?, tagline = ?,
    official_rating = ?, age_rating = ?, community_rating = ?, runtime_ms = ?, metadata_at = ?, updated_at = ?
WHERE id = ?
`

type UpdateItemMetadataParams struct {
	Title           string
	SortTitle       string
	OriginalTitle   string
	Year            int64
	PremiereDate    string
	Overview        string
	Tagline         string
	OfficialRating  string
	AgeRating       sql.NullInt64
	CommunityRating float64
	RuntimeMs       int64
	MetadataAt      sql.NullInt64
	UpdatedAt       int64
	ID              domain.ID
}

func (q *Queries) UpdateItemMetadata(ctx context.Context, arg UpdateItemMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateItemMetadata,
		arg.Title,
		arg.SortTitle,
		arg.OriginalTitle,
		arg.Year,
		arg.PremiereDate,
		arg.Overview,
		arg.Tagline,
		arg.OfficialRating,
		arg.AgeRating,
		arg.CommunityRating,
		arg.RuntimeMs,
		arg.MetadataAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
