// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlc

import (
	"context"
)

const claimJob = `-- name: ClaimJob :one
UPDATE jobs
SET state = 'running', attempts = attempts + 1, updated_at = ?
WHERE id = (SELECT j.id FROM jobs j
            WHERE j.class = ? AND j.state = 'pending' AND j.run_after <= ?
            ORDER BY j.priority DESC, j.id
            LIMIT 1)
RETURNING id, kind, target, attempts
`

type ClaimJobParams struct {
	UpdatedAt int64
	Class     string
	RunAfter  int64
}

type ClaimJobRow struct {
	ID       int64
	Kind     string
	Target   string
	Attempts int64
}

func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (ClaimJobRow, error) {
	row := q.db.QueryRowContext(ctx, claimJob, arg.UpdatedAt, arg.Class, arg.RunAfter)
	var i ClaimJobRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Target,
		&i.Attempts,
	)
	return i, err
}

const countJobs = `-- name: CountJobs :many
SELECT kind, state, count(*) AS n FROM jobs GROUP BY kind, state ORDER BY kind, state
`

type CountJobsRow struct {
	Kind  string
	State string
	N     int64
}

func (q *Queries) CountJobs(ctx context.Context) ([]CountJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, countJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountJobsRow{}
	for rows.Next() {
		var i CountJobsRow
		if err := rows.Scan(&i.Kind, &i.State, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs WHERE id = ?
`

func (q *Queries) DeleteJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteJob, id)
	return err
}

const deleteRunningJobs = `-- name: DeleteRunningJobs :exec
DELETE FROM jobs WHERE state = 'running'
`

func (q *Queries) DeleteRunningJobs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteRunningJobs)
	return err
}

const enqueueJob = `-- name: EnqueueJob :exec
INSERT INTO jobs (kind, target, class, priority, state, attempts, run_after, created_at, updated_at)
VALUES (?, ?, ?, ?, 'pending', 0, ?, ?, ?)
ON CONFLICT (kind, target) WHERE state = 'pending'
DO UPDATE SET priority = max(priority, excluded.priority), run_after = min(run_after, excluded.run_after),
              updated_at = excluded.updated_at
`

type EnqueueJobParams struct {
	Kind      string
	Target    string
	Class     string
	Priority  int64
	RunAfter  int64
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) error {
	_, err := q.db.ExecContext(ctx, enqueueJob,
		arg.Kind,
		arg.Target,
		arg.Class,
		arg.Priority,
		arg.RunAfter,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const failJob = `-- name: FailJob :exec
UPDATE jobs SET state = 'failed', last_error = ?, updated_at = ? WHERE id = ?
`

type FailJobParams struct {
	LastError string
	UpdatedAt int64
	ID        int64
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.ExecContext(ctx, failJob, arg.LastError, arg.UpdatedAt, arg.ID)
	return err
}

const nextJobTime = `-- name: NextJobTime :one
SELECT CAST(coalesce(min(run_after), 0) AS INTEGER) AS next FROM jobs WHERE class = ? AND state = 'pending'
`

func (q *Queries) NextJobTime(ctx context.Context, class string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextJobTime, class)
	var next int64
	err := row.Scan(&next)
	return next, err
}

const requeueRunningJobs = `-- name: RequeueRunningJobs :exec
UPDATE OR IGNORE jobs SET state = 'pending', updated_at = ? WHERE state = 'running'
`

func (q *Queries) RequeueRunningJobs(ctx context.Context, updatedAt int64) error {
	_, err := q.db.ExecContext(ctx, requeueRunningJobs, updatedAt)
	return err
}

const retryJob = `-- name: RetryJob :exec
UPDATE jobs SET state = 'pending', run_after = ?, last_error = ?, updated_at = ? WHERE id = ?
`

type RetryJobParams struct {
	RunAfter  int64
	LastError string
	UpdatedAt int64
	ID        int64
}

func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) error {
	_, err := q.db.ExecContext(ctx, retryJob,
		arg.RunAfter,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setJobsClass = `-- name: SetJobsClass :exec
UPDATE jobs SET class = ?1 WHERE kind = ?2 AND class <> ?1
`

type SetJobsClassParams struct {
	Class string
	Kind  string
}

func (q *Queries) SetJobsClass(ctx context.Context, arg SetJobsClassParams) error {
	_, err := q.db.ExecContext(ctx, setJobsClass, arg.Class, arg.Kind)
	return err
}
