// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keyframes.sql

package sqlc

import (
	"context"

	"github.com/laterna-project/laterna/internal/domain"
)

const getKeyframes = `-- name: GetKeyframes :one
SELECT times FROM keyframes WHERE file_id = ? AND fingerprint = ?
`

type GetKeyframesParams struct {
	FileID      domain.ID
	Fingerprint string
}

func (q *Queries) GetKeyframes(ctx context.Context, arg GetKeyframesParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getKeyframes, arg.FileID, arg.Fingerprint)
	var times string
	err := row.Scan(&times)
	return times, err
}

const upsertKeyframes = `-- name: UpsertKeyframes :exec
INSERT INTO keyframes (file_id, fingerprint, times, created_at) VALUES (?, ?, ?, ?)
ON CONFLICT (file_id) DO UPDATE
SET fingerprint = excluded.fingerprint, times = excluded.times, created_at = excluded.created_at
`

type UpsertKeyframesParams struct {
	FileID      domain.ID
	Fingerprint string
	Times       string
	CreatedAt   int64
}

func (q *Queries) UpsertKeyframes(ctx context.Context, arg UpsertKeyframesParams) error {
	_, err := q.db.ExecContext(ctx, upsertKeyframes,
		arg.FileID,
		arg.Fingerprint,
		arg.Times,
		arg.CreatedAt,
	)
	return err
}
