// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: library.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/laterna-project/laterna/internal/domain"
)

const countLibraryItems = `-- name: CountLibraryItems :many
SELECT kind, count(*) AS n FROM items WHERE library_id = ? GROUP BY kind
`

type CountLibraryItemsRow struct {
	Kind string
	N    int64
}

func (q *Queries) CountLibraryItems(ctx context.Context, libraryID domain.ID) ([]CountLibraryItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, countLibraryItems, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountLibraryItemsRow{}
	for rows.Next() {
		var i CountLibraryItemsRow
		if err := rows.Scan(&i.Kind, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteLibrary = `-- name: DeleteLibrary :exec
DELETE FROM libraries WHERE id = ?
`

func (q *Queries) DeleteLibrary(ctx context.Context, id domain.ID) error {
	_, err := q.db.ExecContext(ctx, deleteLibrary, id)
	return err
}

const deleteLibraryPaths = `-- name: DeleteLibraryPaths :exec
DELETE FROM library_paths WHERE library_id = ?
`

func (q *Queries) DeleteLibraryPaths(ctx context.Context, libraryID domain.ID) error {
	_, err := q.db.ExecContext(ctx, deleteLibraryPaths, libraryID)
	return err
}

const deleteMetadataDir = `-- name: DeleteMetadataDir :exec
DELETE FROM metadata_dirs WHERE library_id = ? AND path = ?
`

type DeleteMetadataDirParams struct {
	LibraryID domain.ID
	Path      string
}

func (q *Queries) DeleteMetadataDir(ctx context.Context, arg DeleteMetadataDirParams) error {
	_, err := q.db.ExecContext(ctx, deleteMetadataDir, arg.LibraryID, arg.Path)
	return err
}

const getLibrary = `-- name: GetLibrary :one
SELECT id, name, name_key, kind, language, created_at, updated_at, last_scan_at, position FROM libraries WHERE id = ?
`

func (q *Queries) GetLibrary(ctx context.Context, id domain.ID) (Library, error) {
	row := q.db.QueryRowContext(ctx, getLibrary, id)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameKey,
		&i.Kind,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastScanAt,
		&i.Position,
	)
	return i, err
}

const insertLibrary = `-- name: InsertLibrary :exec
INSERT INTO libraries (id, name, name_key, kind, language, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertLibraryParams struct {
	ID        domain.ID
	Name      string
	NameKey   string
	Kind      string
	Language  string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) InsertLibrary(ctx context.Context, arg InsertLibraryParams) error {
	_, err := q.db.ExecContext(ctx, insertLibrary,
		arg.ID,
		arg.Name,
		arg.NameKey,
		arg.Kind,
		arg.Language,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertLibraryPath = `-- name: InsertLibraryPath :exec
INSERT INTO library_paths (library_id, path) VALUES (?, ?)
`

type InsertLibraryPathParams struct {
	LibraryID domain.ID
	Path      string
}

func (q *Queries) InsertLibraryPath(ctx context.Context, arg InsertLibraryPathParams) error {
	_, err := q.db.ExecContext(ctx, insertLibraryPath, arg.LibraryID, arg.Path)
	return err
}

const listAllLibraryPaths = `-- name: ListAllLibraryPaths :many
SELECT library_id, path FROM library_paths ORDER BY path
`

func (q *Queries) ListAllLibraryPaths(ctx context.Context) ([]LibraryPath, error) {
	rows, err := q.db.QueryContext(ctx, listAllLibraryPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LibraryPath{}
	for rows.Next() {
		var i LibraryPath
		if err := rows.Scan(&i.LibraryID, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraries = `-- name: ListLibraries :many
SELECT id, name, name_key, kind, language, created_at, updated_at, last_scan_at, position FROM libraries
ORDER BY position = 0, position,
         CASE kind WHEN 'movies' THEN 0 WHEN 'shows' THEN 1 WHEN 'music' THEN 2 WHEN 'books' THEN 3 ELSE 4 END,
         name_key
`

func (q *Queries) ListLibraries(ctx context.Context) ([]Library, error) {
	rows, err := q.db.QueryContext(ctx, listLibraries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Library{}
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameKey,
			&i.Kind,
			&i.Language,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastScanAt,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraryPaths = `-- name: ListLibraryPaths :many
SELECT path FROM library_paths WHERE library_id = ? ORDER BY path
`

func (q *Queries) ListLibraryPaths(ctx context.Context, libraryID domain.ID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listLibraryPaths, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetadataDirs = `-- name: ListMetadataDirs :many
SELECT path, signature FROM metadata_dirs WHERE library_id = ?
`

type ListMetadataDirsRow struct {
	Path      string
	Signature string
}

func (q *Queries) ListMetadataDirs(ctx context.Context, libraryID domain.ID) ([]ListMetadataDirsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMetadataDirs, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMetadataDirsRow{}
	for rows.Next() {
		var i ListMetadataDirsRow
		if err := rows.Scan(&i.Path, &i.Signature); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLibraryPosition = `-- name: SetLibraryPosition :exec
UPDATE libraries SET position = ? WHERE id = ?
`

type SetLibraryPositionParams struct {
	Position int64
	ID       domain.ID
}

func (q *Queries) SetLibraryPosition(ctx context.Context, arg SetLibraryPositionParams) error {
	_, err := q.db.ExecContext(ctx, setLibraryPosition, arg.Position, arg.ID)
	return err
}

const setLibraryScanned = `-- name: SetLibraryScanned :exec
UPDATE libraries SET last_scan_at = ? WHERE id = ?
`

type SetLibraryScannedParams struct {
	LastScanAt sql.NullInt64
	ID         domain.ID
}

func (q *Queries) SetLibraryScanned(ctx context.Context, arg SetLibraryScannedParams) error {
	_, err := q.db.ExecContext(ctx, setLibraryScanned, arg.LastScanAt, arg.ID)
	return err
}

const updateLibrary = `-- name: UpdateLibrary :exec
UPDATE libraries SET name = ?, name_key = ?, language = ?, updated_at = ? WHERE id = ?
`

type UpdateLibraryParams struct {
	Name      string
	NameKey   string
	Language  string
	UpdatedAt int64
	ID        domain.ID
}

func (q *Queries) UpdateLibrary(ctx context.Context, arg UpdateLibraryParams) error {
	_, err := q.db.ExecContext(ctx, updateLibrary,
		arg.Name,
		arg.NameKey,
		arg.Language,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertMetadataDir = `-- name: UpsertMetadataDir :exec
INSERT INTO metadata_dirs (library_id, path, signature) VALUES (?, ?, ?)
ON CONFLICT (library_id, path) DO UPDATE SET signature = excluded.signature
`

type UpsertMetadataDirParams struct {
	LibraryID domain.ID
	Path      string
	Signature string
}

func (q *Queries) UpsertMetadataDir(ctx context.Context, arg UpsertMetadataDirParams) error {
	_, err := q.db.ExecContext(ctx, upsertMetadataDir, arg.LibraryID, arg.Path, arg.Signature)
	return err
}
