// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"

	"github.com/laterna-project/laterna/internal/domain"
)

type Account struct {
	ID                  domain.ID
	Username            string
	UsernameKey         string
	PasswordHash        string
	IsAdmin             int64
	Disabled            int64
	CreatedAt           int64
	UpdatedAt           int64
	AllLibraries        int64
	MaxAge              sql.NullInt64
	BlockUnrated        int64
	DenyDownloads       int64
	DenyRequests        int64
	AutoApproveRequests int64
	RequestQuota        int64
}

type AccountLibrary struct {
	AccountID domain.ID
	LibraryID domain.ID
}

type Activity struct {
	ID        int64
	At        int64
	Kind      string
	Warning   int64
	AccountID *domain.ID
	ProfileID *domain.ID
	ItemID    *domain.ID
	Message   string
}

type Book struct {
	ItemID    domain.ID
	Number    float64
	Publisher string
	Language  string
	Isbn      string
}

type BookFile struct {
	FileID      domain.ID
	Format      string
	Layout      string
	RightToLeft int64
	PageCount   int64
	Pages       string
	AccessKey   string
}

type Chapter struct {
	FileID  domain.ID
	Idx     int64
	StartMs int64
	EndMs   int64
	Title   string
}

type Collection struct {
	ID        domain.ID
	Name      string
	Overview  string
	NfoKey    string
	CreatedAt int64
	UpdatedAt int64
}

type CollectionItem struct {
	CollectionID domain.ID
	ItemID       domain.ID
	AddedAt      int64
}

type Download struct {
	ID        domain.ID
	AccountID domain.ID
	ProfileID domain.ID
	SessionID domain.ID
	ItemID    domain.ID
	FileID    domain.ID
	Quality   string
	State     string
	Plan      string
	Progress  float64
	Estimate  int64
	Size      int64
	Path      string
	Error     string
	CreatedAt int64
	UpdatedAt int64
	ReadyAt   sql.NullInt64
}

type Episode struct {
	ItemID       domain.ID
	SeriesID     domain.ID
	SeasonID     domain.ID
	SeasonNumber int64
	Number       int64
	NumberEnd    int64
	Absolute     int64
}

type FileFont struct {
	FileID domain.ID
	Sha256 string
}

type Font struct {
	Sha256 string
	Names  string
	Ext    string
	Size   int64
}

type Image struct {
	ID        domain.ID
	ItemID    *domain.ID
	PersonID  *domain.ID
	ThemeID   *domain.ID
	Kind      string
	Source    string
	Path      string
	RemoteUrl string
	Width     int64
	Height    int64
	Blurhash  string
	Hash      string
	UpdatedAt int64
}

type Item struct {
	ID              domain.ID
	LibraryID       domain.ID
	Kind            string
	ParentID        *domain.ID
	GroupKey        string
	Title           string
	SortTitle       string
	OriginalTitle   string
	Year            int64
	PremiereDate    string
	Overview        string
	Tagline         string
	OfficialRating  string
	CommunityRating float64
	RuntimeMs       int64
	MetadataAt      sql.NullInt64
	AddedAt         int64
	UpdatedAt       int64
	AgeRating       sql.NullInt64
	Present         int64
}

type ItemFile struct {
	ItemID  domain.ID
	FileID  domain.ID
	Version string
	Part    int64
}

type ItemGenre struct {
	ItemID domain.ID
	Genre  string
}

type ItemPerson struct {
	ItemID    domain.ID
	PersonID  domain.ID
	Role      string
	Character string
	SortOrder int64
}

type ItemStudio struct {
	ItemID domain.ID
	Studio string
}

type ItemsFt struct {
	Title         string
	OriginalTitle string
}

type Job struct {
	ID        int64
	Kind      string
	Target    string
	Class     string
	Priority  int64
	State     string
	Attempts  int64
	RunAfter  int64
	LastError string
	CreatedAt int64
	UpdatedAt int64
}

type Keyframe struct {
	FileID      domain.ID
	Fingerprint string
	Times       string
	CreatedAt   int64
}

type Library struct {
	ID         domain.ID
	Name       string
	NameKey    string
	Kind       string
	Language   string
	CreatedAt  int64
	UpdatedAt  int64
	LastScanAt sql.NullInt64
	Position   int64
}

type LibraryPath struct {
	LibraryID domain.ID
	Path      string
}

type MediaFile struct {
	ID            domain.ID
	LibraryID     domain.ID
	Path          string
	Size          int64
	Mtime         int64
	Fingerprint   string
	MissingSince  sql.NullInt64
	AnalyzedAt    sql.NullInt64
	AnalysisError string
	Container     string
	DurationMs    int64
	Bitrate       int64
	CreatedAt     int64
	UpdatedAt     int64
	Tags          string
}

type MediaSegment struct {
	FileID  domain.ID
	Kind    string
	StartMs int64
	EndMs   int64
	Source  string
}

type MediaStream struct {
	FileID            domain.ID
	Idx               int64
	Kind              string
	Codec             string
	Profile           string
	Language          string
	Title             string
	IsDefault         int64
	IsForced          int64
	IsHearingImpaired int64
	Width             int64
	Height            int64
	BitDepth          int64
	FrameRate         float64
	DynamicRange      string
	PixelFormat       string
	Channels          int64
	ChannelLayout     string
	SampleRate        int64
	Bitrate           int64
}

type MetadataDir struct {
	LibraryID domain.ID
	Path      string
	Signature string
}

type OfflinePlay struct {
	ProfileID domain.ID
	ItemID    domain.ID
	PlayedAt  int64
}

type OidcLink struct {
	Issuer    string
	Subject   string
	AccountID domain.ID
	CreatedAt int64
}

type Passkey struct {
	ID           domain.ID
	AccountID    domain.ID
	CredentialID string
	PublicKey    string
	SignCount    int64
	Name         string
	CreatedAt    int64
	LastUsedAt   sql.NullInt64
}

type Person struct {
	ID        domain.ID
	Name      string
	NameKey   string
	CreatedAt int64
}

type Photo struct {
	ItemID       domain.ID
	TakenAt      int64
	UtcOffset    sql.NullInt64
	Width        int64
	Height       int64
	Make         string
	Model        string
	Lens         string
	FNumber      float64
	ExposureTime string
	Iso          int64
	FocalLength  float64
	Latitude     sql.NullFloat64
	Longitude    sql.NullFloat64
}

type PlayHistory struct {
	ID         domain.ID
	ProfileID  domain.ID
	ItemID     *domain.ID
	Kind       string
	SeriesID   *domain.ID
	AlbumID    *domain.ID
	ArtistID   *domain.ID
	Title      string
	Subtitle   string
	StartedAt  int64
	EndedAt    int64
	WatchedMs  int64
	PositionMs int64
	DurationMs int64
	Completed  int64
	Device     string
	Offline    int64
	ImportKey  sql.NullString
}

type Playlist struct {
	ID        domain.ID
	ProfileID domain.ID
	Name      string
	CreatedAt int64
	UpdatedAt int64
}

type PlaylistEntry struct {
	ID         domain.ID
	PlaylistID domain.ID
	ItemID     domain.ID
	Position   int64
	AddedAt    int64
}

type Profile struct {
	ID               domain.ID
	AccountID        domain.ID
	Name             string
	NameKey          string
	PinHash          sql.NullString
	Kid              int64
	CreatedAt        int64
	UpdatedAt        int64
	MaxAge           sql.NullInt64
	BlockUnrated     int64
	ThemeID          *domain.ID
	ThemeMode        string
	Language         string
	SubtitleMode     string
	SubtitleLanguage string
}

type ProviderID struct {
	ItemID   domain.ID
	Provider string
	Value    string
}

type ReadingProgress struct {
	ProfileID   domain.ID
	ItemID      domain.ID
	Page        int64
	Locator     string
	Progression float64
	UpdatedAt   int64
}

type Request struct {
	ID                domain.ID
	Kind              string
	ExternalID        int64
	Title             string
	Year              int64
	Poster            string
	Status            string
	Seasons           string
	SeasonNumbers     string
	DestinationID     *domain.ID
	AccountID         domain.ID
	ProfileID         domain.ID
	CreatedAt         int64
	UpdatedAt         int64
	DecidedAt         sql.NullInt64
	DecidedBy         string
	DeclineReason     string
	Error             string
	ArrID             int64
	Progress          float64
	ItemID            *domain.ID
	EpisodesAvailable int64
	EpisodesWanted    int64
	AvailableAt       sql.NullInt64
}

type RequestDestination struct {
	ID                 domain.ID
	Name               string
	NameKey            string
	Kind               string
	LibraryID          domain.ID
	RootFolder         string
	QualityProfileID   int64
	QualityProfileName string
	SeriesType         string
	CreatedAt          int64
	UpdatedAt          int64
}

type Season struct {
	ItemID   domain.ID
	SeriesID domain.ID
	Number   int64
}

type SegmentScan struct {
	FileID      domain.ID
	Fingerprint string
	Audio       int64
	ScannedAt   int64
}

type Session struct {
	ID            domain.ID
	AccountID     domain.ID
	ProfileID     *domain.ID
	TokenHash     string
	DeviceName    string
	Client        string
	ClientVersion string
	Platform      string
	CreatedAt     int64
	LastUsedAt    int64
	ExpiresAt     int64
	LastIp        string
}

type Setting struct {
	Key   string
	Value string
}

type Subtitle struct {
	FileID            domain.ID
	Position          int64
	StreamIdx         int64
	Path              string
	Codec             string
	Language          string
	Title             string
	IsDefault         int64
	IsForced          int64
	IsHearingImpaired int64
	Formats           string
	Width             int64
	Height            int64
}

type SubtitleSet struct {
	FileID      domain.ID
	Fingerprint string
	Sidecars    string
	ExtractedAt int64
}

type Theme struct {
	ID        domain.ID
	Name      string
	NameKey   string
	BuiltIn   int64
	Tokens    string
	CreatedAt int64
	UpdatedAt int64
}

type Track struct {
	ItemID    domain.ID
	AlbumID   domain.ID
	ArtistID  domain.ID
	Disc      int64
	Number    int64
	Artists   string
	TrackGain sql.NullFloat64
	TrackPeak sql.NullFloat64
	AlbumGain sql.NullFloat64
	AlbumPeak sql.NullFloat64
}

type Trickplay struct {
	FileID      domain.ID
	Fingerprint string
	Key         string
	IntervalMs  int64
	Width       int64
	Height      int64
	Columns     int64
	Rows        int64
	Count       int64
	Sheets      int64
	CreatedAt   int64
}

type UserDatum struct {
	ProfileID    domain.ID
	ItemID       domain.ID
	Played       int64
	PlayCount    int64
	PositionMs   int64
	LastPlayedAt sql.NullInt64
	Favorite     int64
	UpdatedAt    int64
}
