// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: music.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/laterna-project/laterna/internal/domain"
)

const albumTrackSummary = `-- name: AlbumTrackSummary :one
SELECT CAST(COALESCE(SUM(i.runtime_ms), 0) AS INTEGER) AS runtime_ms, CAST(COALESCE(MAX(i.year), 0) AS INTEGER) AS year
FROM tracks t
JOIN items i ON i.id = t.item_id
WHERE t.album_id = ? AND EXISTS (
    SELECT 1 FROM item_files l JOIN media_files f ON f.id = l.file_id
    WHERE l.item_id = t.item_id AND f.missing_since IS NULL
)
`

type AlbumTrackSummaryRow struct {
	RuntimeMs int64
	Year      int64
}

func (q *Queries) AlbumTrackSummary(ctx context.Context, albumID domain.ID) (AlbumTrackSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, albumTrackSummary, albumID)
	var i AlbumTrackSummaryRow
	err := row.Scan(&i.RuntimeMs, &i.Year)
	return i, err
}

const firstFileOfArtist = `-- name: FirstFileOfArtist :one
SELECT f.id, f.path
FROM media_files f
JOIN item_files l ON l.file_id = f.id
JOIN tracks t ON t.item_id = l.item_id
JOIN items a ON a.id = t.album_id
WHERE t.artist_id = ? AND f.missing_since IS NULL
ORDER BY a.year, a.sort_title, t.disc, t.number
LIMIT 1
`

type FirstFileOfArtistRow struct {
	ID   domain.ID
	Path string
}

func (q *Queries) FirstFileOfArtist(ctx context.Context, artistID domain.ID) (FirstFileOfArtistRow, error) {
	row := q.db.QueryRowContext(ctx, firstFileOfArtist, artistID)
	var i FirstFileOfArtistRow
	err := row.Scan(&i.ID, &i.Path)
	return i, err
}

const getTrack = `-- name: GetTrack :one
SELECT item_id, album_id, artist_id, disc, number, artists, track_gain, track_peak, album_gain, album_peak FROM tracks WHERE item_id = ?
`

func (q *Queries) GetTrack(ctx context.Context, itemID domain.ID) (Track, error) {
	row := q.db.QueryRowContext(ctx, getTrack, itemID)
	var i Track
	err := row.Scan(
		&i.ItemID,
		&i.AlbumID,
		&i.ArtistID,
		&i.Disc,
		&i.Number,
		&i.Artists,
		&i.TrackGain,
		&i.TrackPeak,
		&i.AlbumGain,
		&i.AlbumPeak,
	)
	return i, err
}

const listAlbumFiles = `-- name: ListAlbumFiles :many
SELECT f.id, f.path
FROM media_files f
JOIN item_files l ON l.file_id = f.id
JOIN tracks t ON t.item_id = l.item_id
WHERE t.album_id = ? AND f.missing_since IS NULL
ORDER BY t.disc, t.number
`

type ListAlbumFilesRow struct {
	ID   domain.ID
	Path string
}

func (q *Queries) ListAlbumFiles(ctx context.Context, albumID domain.ID) ([]ListAlbumFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumFiles, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlbumFilesRow{}
	for rows.Next() {
		var i ListAlbumFilesRow
		if err := rows.Scan(&i.ID, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumTrackGenres = `-- name: ListAlbumTrackGenres :many
SELECT g.genre
FROM item_genres g
JOIN tracks t ON t.item_id = g.item_id
WHERE t.album_id = ?
GROUP BY g.genre
ORDER BY COUNT(*) DESC, g.genre
`

func (q *Queries) ListAlbumTrackGenres(ctx context.Context, albumID domain.ID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumTrackGenres, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var genre string
		if err := rows.Scan(&genre); err != nil {
			return nil, err
		}
		items = append(items, genre)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumTrackIDs = `-- name: ListAlbumTrackIDs :many
SELECT item_id FROM tracks WHERE album_id = ? ORDER BY disc, number
`

func (q *Queries) ListAlbumTrackIDs(ctx context.Context, albumID domain.ID) ([]domain.ID, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumTrackIDs, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []domain.ID{}
	for rows.Next() {
		var item_id domain.ID
		if err := rows.Scan(&item_id); err != nil {
			return nil, err
		}
		items = append(items, item_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtistTrackIDs = `-- name: ListArtistTrackIDs :many
SELECT t.item_id
FROM tracks t
JOIN items a ON a.id = t.album_id
WHERE t.artist_id = ?
ORDER BY a.year, a.sort_title, t.disc, t.number
`

func (q *Queries) ListArtistTrackIDs(ctx context.Context, artistID domain.ID) ([]domain.ID, error) {
	rows, err := q.db.QueryContext(ctx, listArtistTrackIDs, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []domain.ID{}
	for rows.Next() {
		var item_id domain.ID
		if err := rows.Scan(&item_id); err != nil {
			return nil, err
		}
		items = append(items, item_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTrack = `-- name: UpsertTrack :exec

INSERT INTO tracks (item_id, album_id, artist_id, disc, number, artists, track_gain, track_peak, album_gain, album_peak)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (item_id) DO UPDATE
SET album_id = excluded.album_id,
    artist_id = excluded.artist_id,
    disc = excluded.disc,
    number = excluded.number,
    artists = excluded.artists,
    track_gain = excluded.track_gain,
    track_peak = excluded.track_peak,
    album_gain = excluded.album_gain,
    album_peak = excluded.album_peak
`

type UpsertTrackParams struct {
	ItemID    domain.ID
	AlbumID   domain.ID
	ArtistID  domain.ID
	Disc      int64
	Number    int64
	Artists   string
	TrackGain sql.NullFloat64
	TrackPeak sql.NullFloat64
	AlbumGain sql.NullFloat64
	AlbumPeak sql.NullFloat64
}

// Music: artists, albums, tracks.
func (q *Queries) UpsertTrack(ctx context.Context, arg UpsertTrackParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrack,
		arg.ItemID,
		arg.AlbumID,
		arg.ArtistID,
		arg.Disc,
		arg.Number,
		arg.Artists,
		arg.TrackGain,
		arg.TrackPeak,
		arg.AlbumGain,
		arg.AlbumPeak,
	)
	return err
}
