// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/laterna-project/laterna/internal/domain"
)

const administratorProfiles = `-- name: AdministratorProfiles :many
SELECT p.id
FROM profiles p
JOIN accounts a ON a.id = p.account_id
WHERE a.is_admin = 1 AND a.disabled = 0 AND p.kid = 0 AND p.max_age IS NULL AND p.block_unrated = 0
ORDER BY p.id
`

// Profiles that can administer: those of enabled administrator accounts, without restriction.
func (q *Queries) AdministratorProfiles(ctx context.Context) ([]domain.ID, error) {
	rows, err := q.db.QueryContext(ctx, administratorProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []domain.ID{}
	for rows.Next() {
		var id domain.ID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications WHERE profile_id = ? AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, profileID domain.ID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, profileID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteNotificationsBefore = `-- name: DeleteNotificationsBefore :execrows
DELETE FROM notifications WHERE created_at < ?
`

func (q *Queries) DeleteNotificationsBefore(ctx context.Context, createdAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNotificationsBefore, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteNotificationsUpTo = `-- name: DeleteNotificationsUpTo :exec
DELETE FROM notifications WHERE profile_id = ? AND id <= ?
`

type DeleteNotificationsUpToParams struct {
	ProfileID domain.ID
	ID        domain.ID
}

func (q *Queries) DeleteNotificationsUpTo(ctx context.Context, arg DeleteNotificationsUpToParams) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationsUpTo, arg.ProfileID, arg.ID)
	return err
}

const insertNotification = `-- name: InsertNotification :exec

INSERT INTO notifications (id, profile_id, kind, text, item_id, request_id, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertNotificationParams struct {
	ID        domain.ID
	ProfileID domain.ID
	Kind      string
	Text      string
	ItemID    *domain.ID
	RequestID *domain.ID
	CreatedAt int64
}

// Notifications of a profile (docs/design/notifications.md). Listing, marking and deleting by ID are
// built in notifications.go.
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.ExecContext(ctx, insertNotification,
		arg.ID,
		arg.ProfileID,
		arg.Kind,
		arg.Text,
		arg.ItemID,
		arg.RequestID,
		arg.CreatedAt,
	)
	return err
}

const notificationAt = `-- name: NotificationAt :one
SELECT id FROM notifications WHERE profile_id = ? ORDER BY id DESC LIMIT 1 OFFSET ?
`

type NotificationAtParams struct {
	ProfileID domain.ID
	Offset    int64
}

// The ID of the notification of a profile at a rank, newest first (rank 0).
func (q *Queries) NotificationAt(ctx context.Context, arg NotificationAtParams) (domain.ID, error) {
	row := q.db.QueryRowContext(ctx, notificationAt, arg.ProfileID, arg.Offset)
	var id domain.ID
	err := row.Scan(&id)
	return id, err
}

const seriesFollowers = `-- name: SeriesFollowers :many
SELECT u.profile_id
FROM user_data u
WHERE u.item_id = ?1 AND u.favorite = 1
UNION
SELECT u.profile_id
FROM user_data u
JOIN episodes e ON e.item_id = u.item_id
WHERE e.series_id = ?1 AND (u.played = 1 OR u.position_ms > 0)
ORDER BY 1
`

// Profiles that follow a series: it is one of their favorites, or they played or started one of its
// episodes.
func (q *Queries) SeriesFollowers(ctx context.Context, seriesID domain.ID) ([]domain.ID, error) {
	rows, err := q.db.QueryContext(ctx, seriesFollowers, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []domain.ID{}
	for rows.Next() {
		var profile_id domain.ID
		if err := rows.Scan(&profile_id); err != nil {
			return nil, err
		}
		items = append(items, profile_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
