// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oidc.sql

package sqlc

import (
	"context"

	"github.com/laterna-project/laterna/internal/domain"
)

const getOidcAccount = `-- name: GetOidcAccount :one
SELECT account_id FROM oidc_links WHERE issuer = ? AND subject = ?
`

type GetOidcAccountParams struct {
	Issuer  string
	Subject string
}

func (q *Queries) GetOidcAccount(ctx context.Context, arg GetOidcAccountParams) (domain.ID, error) {
	row := q.db.QueryRowContext(ctx, getOidcAccount, arg.Issuer, arg.Subject)
	var account_id domain.ID
	err := row.Scan(&account_id)
	return account_id, err
}

const insertOidcLink = `-- name: InsertOidcLink :exec
INSERT INTO oidc_links (issuer, subject, account_id, created_at) VALUES (?, ?, ?, ?)
`

type InsertOidcLinkParams struct {
	Issuer    string
	Subject   string
	AccountID domain.ID
	CreatedAt int64
}

func (q *Queries) InsertOidcLink(ctx context.Context, arg InsertOidcLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertOidcLink,
		arg.Issuer,
		arg.Subject,
		arg.AccountID,
		arg.CreatedAt,
	)
	return err
}
