// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: passkeys.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/laterna-project/laterna/internal/domain"
)

const deletePasskey = `-- name: DeletePasskey :execrows
DELETE FROM passkeys WHERE id = ? AND account_id = ?
`

type DeletePasskeyParams struct {
	ID        domain.ID
	AccountID domain.ID
}

func (q *Queries) DeletePasskey(ctx context.Context, arg DeletePasskeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePasskey, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPasskeyByCredential = `-- name: GetPasskeyByCredential :one
SELECT id, account_id, credential_id, public_key, sign_count, name, created_at, last_used_at FROM passkeys WHERE credential_id = ?
`

func (q *Queries) GetPasskeyByCredential(ctx context.Context, credentialID string) (Passkey, error) {
	row := q.db.QueryRowContext(ctx, getPasskeyByCredential, credentialID)
	var i Passkey
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CredentialID,
		&i.PublicKey,
		&i.SignCount,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const insertPasskey = `-- name: InsertPasskey :exec
INSERT INTO passkeys (id, account_id, credential_id, public_key, sign_count, name, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertPasskeyParams struct {
	ID           domain.ID
	AccountID    domain.ID
	CredentialID string
	PublicKey    string
	SignCount    int64
	Name         string
	CreatedAt    int64
}

func (q *Queries) InsertPasskey(ctx context.Context, arg InsertPasskeyParams) error {
	_, err := q.db.ExecContext(ctx, insertPasskey,
		arg.ID,
		arg.AccountID,
		arg.CredentialID,
		arg.PublicKey,
		arg.SignCount,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const listAccountPasskeys = `-- name: ListAccountPasskeys :many
SELECT id, account_id, credential_id, public_key, sign_count, name, created_at, last_used_at FROM passkeys WHERE account_id = ? ORDER BY created_at, id
`

func (q *Queries) ListAccountPasskeys(ctx context.Context, accountID domain.ID) ([]Passkey, error) {
	rows, err := q.db.QueryContext(ctx, listAccountPasskeys, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Passkey{}
	for rows.Next() {
		var i Passkey
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CredentialID,
			&i.PublicKey,
			&i.SignCount,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchPasskey = `-- name: TouchPasskey :exec
UPDATE passkeys SET sign_count = ?, last_used_at = ? WHERE id = ?
`

type TouchPasskeyParams struct {
	SignCount  int64
	LastUsedAt sql.NullInt64
	ID         domain.ID
}

func (q *Queries) TouchPasskey(ctx context.Context, arg TouchPasskeyParams) error {
	_, err := q.db.ExecContext(ctx, touchPasskey, arg.SignCount, arg.LastUsedAt, arg.ID)
	return err
}
