// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photos.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/laterna-project/laterna/internal/domain"
)

const deleteEmptyPhotoAlbums = `-- name: DeleteEmptyPhotoAlbums :execrows
DELETE FROM items
WHERE items.library_id = ? AND items.kind = 'photo_album'
  AND NOT EXISTS (SELECT 1 FROM items c WHERE c.parent_id = items.id)
`

func (q *Queries) DeleteEmptyPhotoAlbums(ctx context.Context, libraryID domain.ID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEmptyPhotoAlbums, libraryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPhoto = `-- name: GetPhoto :one
SELECT item_id, taken_at, utc_offset, width, height, make, model, lens, f_number, exposure_time, iso, focal_length, latitude, longitude FROM photos WHERE item_id = ?
`

func (q *Queries) GetPhoto(ctx context.Context, itemID domain.ID) (Photo, error) {
	row := q.db.QueryRowContext(ctx, getPhoto, itemID)
	var i Photo
	err := row.Scan(
		&i.ItemID,
		&i.TakenAt,
		&i.UtcOffset,
		&i.Width,
		&i.Height,
		&i.Make,
		&i.Model,
		&i.Lens,
		&i.FNumber,
		&i.ExposureTime,
		&i.Iso,
		&i.FocalLength,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const upsertPhoto = `-- name: UpsertPhoto :exec

INSERT INTO photos (item_id, taken_at, utc_offset, width, height, make, model, lens, f_number, exposure_time, iso,
                    focal_length, latitude, longitude)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (item_id) DO UPDATE
SET taken_at = excluded.taken_at,
    utc_offset = excluded.utc_offset,
    width = excluded.width,
    height = excluded.height,
    make = excluded.make,
    model = excluded.model,
    lens = excluded.lens,
    f_number = excluded.f_number,
    exposure_time = excluded.exposure_time,
    iso = excluded.iso,
    focal_length = excluded.focal_length,
    latitude = excluded.latitude,
    longitude = excluded.longitude
`

type UpsertPhotoParams struct {
	ItemID       domain.ID
	TakenAt      int64
	UtcOffset    sql.NullInt64
	Width        int64
	Height       int64
	Make         string
	Model        string
	Lens         string
	FNumber      float64
	ExposureTime string
	Iso          int64
	FocalLength  float64
	Latitude     sql.NullFloat64
	Longitude    sql.NullFloat64
}

// Photos: photos and albums.
func (q *Queries) UpsertPhoto(ctx context.Context, arg UpsertPhotoParams) error {
	_, err := q.db.ExecContext(ctx, upsertPhoto,
		arg.ItemID,
		arg.TakenAt,
		arg.UtcOffset,
		arg.Width,
		arg.Height,
		arg.Make,
		arg.Model,
		arg.Lens,
		arg.FNumber,
		arg.ExposureTime,
		arg.Iso,
		arg.FocalLength,
		arg.Latitude,
		arg.Longitude,
	)
	return err
}
