// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push.sql

package sqlc

import (
	"context"

	"github.com/laterna-project/laterna/internal/domain"
)

const deletePushEndpoint = `-- name: DeletePushEndpoint :execrows

DELETE FROM push_subscriptions WHERE endpoint = ?
`

// Web push subscriptions of the devices (docs/design/notifications.md).
func (q *Queries) DeletePushEndpoint(ctx context.Context, endpoint string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePushEndpoint, endpoint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePushSubscription = `-- name: DeletePushSubscription :execrows
DELETE FROM push_subscriptions WHERE session_id = ?
`

func (q *Queries) DeletePushSubscription(ctx context.Context, sessionID domain.ID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePushSubscription, sessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getNotification = `-- name: GetNotification :one
SELECT id, profile_id, kind, text, item_id, request_id, created_at, read_at FROM notifications WHERE id = ?
`

func (q *Queries) GetNotification(ctx context.Context, id domain.ID) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Kind,
		&i.Text,
		&i.ItemID,
		&i.RequestID,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const getPushEndpoint = `-- name: GetPushEndpoint :one
SELECT endpoint FROM push_subscriptions WHERE session_id = ?
`

func (q *Queries) GetPushEndpoint(ctx context.Context, sessionID domain.ID) (string, error) {
	row := q.db.QueryRowContext(ctx, getPushEndpoint, sessionID)
	var endpoint string
	err := row.Scan(&endpoint)
	return endpoint, err
}

const profilePushSubscriptions = `-- name: ProfilePushSubscriptions :many
SELECT p.session_id, p.endpoint, p.p256dh, p.auth
FROM push_subscriptions p
JOIN sessions s ON s.id = p.session_id
WHERE s.profile_id = ? AND s.expires_at > ?
ORDER BY p.session_id
`

type ProfilePushSubscriptionsParams struct {
	ProfileID *domain.ID
	ExpiresAt int64
}

type ProfilePushSubscriptionsRow struct {
	SessionID domain.ID
	Endpoint  string
	P256dh    string
	Auth      string
}

// Subscriptions of the devices a profile is picked on, whose session is still valid.
func (q *Queries) ProfilePushSubscriptions(ctx context.Context, arg ProfilePushSubscriptionsParams) ([]ProfilePushSubscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, profilePushSubscriptions, arg.ProfileID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProfilePushSubscriptionsRow{}
	for rows.Next() {
		var i ProfilePushSubscriptionsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :exec
INSERT INTO push_subscriptions (session_id, endpoint, p256dh, auth, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (session_id) DO UPDATE
SET endpoint = excluded.endpoint, p256dh = excluded.p256dh, auth = excluded.auth, created_at = excluded.created_at
`

type UpsertPushSubscriptionParams struct {
	SessionID domain.ID
	Endpoint  string
	P256dh    string
	Auth      string
	CreatedAt int64
}

func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, upsertPushSubscription,
		arg.SessionID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
		arg.CreatedAt,
	)
	return err
}
