// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/laterna-project/laterna/internal/domain"
)

const countPendingRequests = `-- name: CountPendingRequests :one
SELECT count(*) FROM requests WHERE status = 'pending'
`

func (q *Queries) CountPendingRequests(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingRequests)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequestsSince = `-- name: CountRequestsSince :one
SELECT count(*) FROM requests WHERE account_id = ? AND created_at >= ?
`

type CountRequestsSinceParams struct {
	AccountID domain.ID
	CreatedAt int64
}

func (q *Queries) CountRequestsSince(ctx context.Context, arg CountRequestsSinceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRequestsSince, arg.AccountID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const declinePendingRequestsTo = `-- name: DeclinePendingRequestsTo :many
UPDATE requests
SET status = 'declined', updated_at = ?1, decided_at = ?1, decided_by = ''
WHERE destination_id = ?2 AND status = 'pending'
RETURNING id, profile_id
`

type DeclinePendingRequestsToParams struct {
	Now           int64
	DestinationID *domain.ID
}

type DeclinePendingRequestsToRow struct {
	ID        domain.ID
	ProfileID domain.ID
}

func (q *Queries) DeclinePendingRequestsTo(ctx context.Context, arg DeclinePendingRequestsToParams) ([]DeclinePendingRequestsToRow, error) {
	rows, err := q.db.QueryContext(ctx, declinePendingRequestsTo, arg.Now, arg.DestinationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeclinePendingRequestsToRow{}
	for rows.Next() {
		var i DeclinePendingRequestsToRow
		if err := rows.Scan(&i.ID, &i.ProfileID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteRequest = `-- name: DeleteRequest :exec
DELETE FROM requests WHERE id = ?
`

func (q *Queries) DeleteRequest(ctx context.Context, id domain.ID) error {
	_, err := q.db.ExecContext(ctx, deleteRequest, id)
	return err
}

const deleteRequestDestination = `-- name: DeleteRequestDestination :exec
DELETE FROM request_destinations WHERE id = ?
`

func (q *Queries) DeleteRequestDestination(ctx context.Context, id domain.ID) error {
	_, err := q.db.ExecContext(ctx, deleteRequestDestination, id)
	return err
}

const insertRequest = `-- name: InsertRequest :exec
INSERT INTO requests (id, kind, external_id, external_key, title, subtitle, year, poster, status, seasons,
                      season_numbers, destination_id, account_id, profile_id, created_at, updated_at, decided_at,
                      decided_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertRequestParams struct {
	ID            domain.ID
	Kind          string
	ExternalID    int64
	ExternalKey   string
	Title         string
	Subtitle      string
	Year          int64
	Poster        string
	Status        string
	Seasons       string
	SeasonNumbers string
	DestinationID *domain.ID
	AccountID     domain.ID
	ProfileID     domain.ID
	CreatedAt     int64
	UpdatedAt     int64
	DecidedAt     sql.NullInt64
	DecidedBy     string
}

func (q *Queries) InsertRequest(ctx context.Context, arg InsertRequestParams) error {
	_, err := q.db.ExecContext(ctx, insertRequest,
		arg.ID,
		arg.Kind,
		arg.ExternalID,
		arg.ExternalKey,
		arg.Title,
		arg.Subtitle,
		arg.Year,
		arg.Poster,
		arg.Status,
		arg.Seasons,
		arg.SeasonNumbers,
		arg.DestinationID,
		arg.AccountID,
		arg.ProfileID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DecidedAt,
		arg.DecidedBy,
	)
	return err
}

const insertRequestDestination = `-- name: InsertRequestDestination :exec

INSERT INTO request_destinations (id, name, name_key, kind, library_id, root_folder, quality_profile_id,
                                  quality_profile_name, series_type, metadata_profile_id, metadata_profile_name,
                                  created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertRequestDestinationParams struct {
	ID                  domain.ID
	Name                string
	NameKey             string
	Kind                string
	LibraryID           domain.ID
	RootFolder          string
	QualityProfileID    int64
	QualityProfileName  string
	SeriesType          string
	MetadataProfileID   int64
	MetadataProfileName string
	CreatedAt           int64
	UpdatedAt           int64
}

// Requests for movies and series, and where they land (docs/design/requests.md).
func (q *Queries) InsertRequestDestination(ctx context.Context, arg InsertRequestDestinationParams) error {
	_, err := q.db.ExecContext(ctx, insertRequestDestination,
		arg.ID,
		arg.Name,
		arg.NameKey,
		arg.Kind,
		arg.LibraryID,
		arg.RootFolder,
		arg.QualityProfileID,
		arg.QualityProfileName,
		arg.SeriesType,
		arg.MetadataProfileID,
		arg.MetadataProfileName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const itemWithExternalID = `-- name: ItemWithExternalID :many
SELECT p.item_id, i.library_id
FROM provider_ids p
JOIN items i ON i.id = p.item_id
WHERE p.provider = ? AND p.value = ?
  AND ((i.kind = 'movie' AND i.present = 1)
    OR (i.kind = 'series' AND EXISTS (SELECT 1 FROM episodes e JOIN items ei ON ei.id = e.item_id
                                      WHERE e.series_id = i.id AND ei.present = 1))
    OR (i.kind = 'album' AND EXISTS (SELECT 1 FROM tracks t JOIN items ti ON ti.id = t.item_id
                                     WHERE t.album_id = i.id AND ti.present = 1))
    OR (i.kind = 'artist' AND EXISTS (SELECT 1 FROM tracks t JOIN items ti ON ti.id = t.item_id
                                      WHERE t.artist_id = i.id AND ti.present = 1)))
`

type ItemWithExternalIDParams struct {
	Provider string
	Value    string
}

type ItemWithExternalIDRow struct {
	ItemID    domain.ID
	LibraryID domain.ID
}

func (q *Queries) ItemWithExternalID(ctx context.Context, arg ItemWithExternalIDParams) ([]ItemWithExternalIDRow, error) {
	rows, err := q.db.QueryContext(ctx, itemWithExternalID, arg.Provider, arg.Value)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemWithExternalIDRow{}
	for rows.Next() {
		var i ItemWithExternalIDRow
		if err := rows.Scan(&i.ItemID, &i.LibraryID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestDestinations = `-- name: ListRequestDestinations :many
SELECT d.id, d.name, d.kind, d.library_id, l.name AS library_name, d.root_folder, d.quality_profile_id,
       d.quality_profile_name, d.series_type, d.metadata_profile_id, d.metadata_profile_name, d.created_at,
       d.updated_at
FROM request_destinations d
JOIN libraries l ON l.id = d.library_id
ORDER BY d.kind, d.name_key
`

type ListRequestDestinationsRow struct {
	ID                  domain.ID
	Name                string
	Kind                string
	LibraryID           domain.ID
	LibraryName         string
	RootFolder          string
	QualityProfileID    int64
	QualityProfileName  string
	SeriesType          string
	MetadataProfileID   int64
	MetadataProfileName string
	CreatedAt           int64
	UpdatedAt           int64
}

func (q *Queries) ListRequestDestinations(ctx context.Context) ([]ListRequestDestinationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRequestDestinations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestDestinationsRow{}
	for rows.Next() {
		var i ListRequestDestinationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.LibraryID,
			&i.LibraryName,
			&i.RootFolder,
			&i.QualityProfileID,
			&i.QualityProfileName,
			&i.SeriesType,
			&i.MetadataProfileID,
			&i.MetadataProfileName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openRequestFor = `-- name: OpenRequestFor :one
SELECT id FROM requests
WHERE kind = ? AND external_id = ? AND external_key = ? AND status IN ('pending', 'approved', 'downloading')
`

type OpenRequestForParams struct {
	Kind        string
	ExternalID  int64
	ExternalKey string
}

func (q *Queries) OpenRequestFor(ctx context.Context, arg OpenRequestForParams) (domain.ID, error) {
	row := q.db.QueryRowContext(ctx, openRequestFor, arg.Kind, arg.ExternalID, arg.ExternalKey)
	var id domain.ID
	err := row.Scan(&id)
	return id, err
}

const requestPosters = `-- name: RequestPosters :many
SELECT DISTINCT poster FROM requests WHERE poster <> ''
`

func (q *Queries) RequestPosters(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, requestPosters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var poster string
		if err := rows.Scan(&poster); err != nil {
			return nil, err
		}
		items = append(items, poster)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestsOnTheirWay = `-- name: RequestsOnTheirWay :many
SELECT id FROM requests
WHERE status IN ('approved', 'downloading')
   OR (status = 'available' AND kind IN ('series', 'artist') AND episodes_available < episodes_wanted
       AND available_at >= ?)
ORDER BY created_at
`

func (q *Queries) RequestsOnTheirWay(ctx context.Context, availableAt sql.NullInt64) ([]domain.ID, error) {
	rows, err := q.db.QueryContext(ctx, requestsOnTheirWay, availableAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []domain.ID{}
	for rows.Next() {
		var id domain.ID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRequest = `-- name: UpdateRequest :exec
UPDATE requests
SET status = ?, seasons = ?, season_numbers = ?, destination_id = ?, updated_at = ?, decided_at = ?, decided_by = ?,
    decline_reason = ?, error = ?, arr_id = ?, progress = ?, item_id = ?, episodes_available = ?,
    episodes_wanted = ?, available_at = ?
WHERE id = ?
`

type UpdateRequestParams struct {
	Status            string
	Seasons           string
	SeasonNumbers     string
	DestinationID     *domain.ID
	UpdatedAt         int64
	DecidedAt         sql.NullInt64
	DecidedBy         string
	DeclineReason     string
	Error             string
	ArrID             int64
	Progress          float64
	ItemID            *domain.ID
	EpisodesAvailable int64
	EpisodesWanted    int64
	AvailableAt       sql.NullInt64
	ID                domain.ID
}

func (q *Queries) UpdateRequest(ctx context.Context, arg UpdateRequestParams) error {
	_, err := q.db.ExecContext(ctx, updateRequest,
		arg.Status,
		arg.Seasons,
		arg.SeasonNumbers,
		arg.DestinationID,
		arg.UpdatedAt,
		arg.DecidedAt,
		arg.DecidedBy,
		arg.DeclineReason,
		arg.Error,
		arg.ArrID,
		arg.Progress,
		arg.ItemID,
		arg.EpisodesAvailable,
		arg.EpisodesWanted,
		arg.AvailableAt,
		arg.ID,
	)
	return err
}

const updateRequestDestination = `-- name: UpdateRequestDestination :exec
UPDATE request_destinations
SET name = ?, name_key = ?, library_id = ?, root_folder = ?, quality_profile_id = ?, quality_profile_name = ?,
    series_type = ?, metadata_profile_id = ?, metadata_profile_name = ?, updated_at = ?
WHERE id = ?
`

type UpdateRequestDestinationParams struct {
	Name                string
	NameKey             string
	LibraryID           domain.ID
	RootFolder          string
	QualityProfileID    int64
	QualityProfileName  string
	SeriesType          string
	MetadataProfileID   int64
	MetadataProfileName string
	UpdatedAt           int64
	ID                  domain.ID
}

func (q *Queries) UpdateRequestDestination(ctx context.Context, arg UpdateRequestDestinationParams) error {
	_, err := q.db.ExecContext(ctx, updateRequestDestination,
		arg.Name,
		arg.NameKey,
		arg.LibraryID,
		arg.RootFolder,
		arg.QualityProfileID,
		arg.QualityProfileName,
		arg.SeriesType,
		arg.MetadataProfileID,
		arg.MetadataProfileName,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
