// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: segments.sql

package sqlc

import (
	"context"

	"github.com/laterna-project/laterna/internal/domain"
)

const deleteFileSegments = `-- name: DeleteFileSegments :exec
DELETE FROM media_segments WHERE file_id = ?
`

func (q *Queries) DeleteFileSegments(ctx context.Context, fileID domain.ID) error {
	_, err := q.db.ExecContext(ctx, deleteFileSegments, fileID)
	return err
}

const deleteFileSegmentsFrom = `-- name: DeleteFileSegmentsFrom :exec
DELETE FROM media_segments WHERE file_id = ? AND source = ?
`

type DeleteFileSegmentsFromParams struct {
	FileID domain.ID
	Source string
}

func (q *Queries) DeleteFileSegmentsFrom(ctx context.Context, arg DeleteFileSegmentsFromParams) error {
	_, err := q.db.ExecContext(ctx, deleteFileSegmentsFrom, arg.FileID, arg.Source)
	return err
}

const getFileEpisode = `-- name: GetFileEpisode :one
SELECT e.item_id, e.season_id, e.number
FROM episodes e
JOIN item_files l ON l.item_id = e.item_id
WHERE l.file_id = ?
`

type GetFileEpisodeRow struct {
	ItemID   domain.ID
	SeasonID domain.ID
	Number   int64
}

func (q *Queries) GetFileEpisode(ctx context.Context, fileID domain.ID) (GetFileEpisodeRow, error) {
	row := q.db.QueryRowContext(ctx, getFileEpisode, fileID)
	var i GetFileEpisodeRow
	err := row.Scan(&i.ItemID, &i.SeasonID, &i.Number)
	return i, err
}

const listFileSegments = `-- name: ListFileSegments :many
SELECT kind, start_ms, end_ms, source FROM media_segments WHERE file_id = ? ORDER BY start_ms
`

type ListFileSegmentsRow struct {
	Kind    string
	StartMs int64
	EndMs   int64
	Source  string
}

func (q *Queries) ListFileSegments(ctx context.Context, fileID domain.ID) ([]ListFileSegmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFileSegments, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFileSegmentsRow{}
	for rows.Next() {
		var i ListFileSegmentsRow
		if err := rows.Scan(
			&i.Kind,
			&i.StartMs,
			&i.EndMs,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasonEpisodeFiles = `-- name: ListSeasonEpisodeFiles :many
SELECT e.item_id, e.number, l.file_id
FROM episodes e
JOIN item_files l ON l.item_id = e.item_id
JOIN media_files m ON m.id = l.file_id
WHERE e.season_id = ? AND m.missing_since IS NULL AND m.analyzed_at IS NOT NULL
ORDER BY e.number, l.part, l.file_id
`

type ListSeasonEpisodeFilesRow struct {
	ItemID domain.ID
	Number int64
	FileID domain.ID
}

func (q *Queries) ListSeasonEpisodeFiles(ctx context.Context, seasonID domain.ID) ([]ListSeasonEpisodeFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSeasonEpisodeFiles, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeasonEpisodeFilesRow{}
	for rows.Next() {
		var i ListSeasonEpisodeFilesRow
		if err := rows.Scan(&i.ItemID, &i.Number, &i.FileID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAudioSegment = `-- name: UpsertAudioSegment :exec
INSERT INTO media_segments (file_id, kind, start_ms, end_ms, source) VALUES (?, ?, ?, ?, 'audio')
ON CONFLICT (file_id, kind) DO UPDATE SET start_ms = excluded.start_ms, end_ms = excluded.end_ms
WHERE media_segments.source = 'audio'
`

type UpsertAudioSegmentParams struct {
	FileID  domain.ID
	Kind    string
	StartMs int64
	EndMs   int64
}

func (q *Queries) UpsertAudioSegment(ctx context.Context, arg UpsertAudioSegmentParams) error {
	_, err := q.db.ExecContext(ctx, upsertAudioSegment,
		arg.FileID,
		arg.Kind,
		arg.StartMs,
		arg.EndMs,
	)
	return err
}

const upsertChapterSegment = `-- name: UpsertChapterSegment :exec
INSERT INTO media_segments (file_id, kind, start_ms, end_ms, source) VALUES (?, ?, ?, ?, 'chapters')
ON CONFLICT (file_id, kind) DO UPDATE SET start_ms = excluded.start_ms, end_ms = excluded.end_ms, source = 'chapters'
`

type UpsertChapterSegmentParams struct {
	FileID  domain.ID
	Kind    string
	StartMs int64
	EndMs   int64
}

func (q *Queries) UpsertChapterSegment(ctx context.Context, arg UpsertChapterSegmentParams) error {
	_, err := q.db.ExecContext(ctx, upsertChapterSegment,
		arg.FileID,
		arg.Kind,
		arg.StartMs,
		arg.EndMs,
	)
	return err
}

const upsertSegmentScan = `-- name: UpsertSegmentScan :exec
INSERT INTO segment_scans (file_id, fingerprint, audio, scanned_at) VALUES (?, ?, ?, ?)
ON CONFLICT (file_id) DO UPDATE SET fingerprint = excluded.fingerprint, audio = excluded.audio,
                                    scanned_at = excluded.scanned_at
`

type UpsertSegmentScanParams struct {
	FileID      domain.ID
	Fingerprint string
	Audio       int64
	ScannedAt   int64
}

func (q *Queries) UpsertSegmentScan(ctx context.Context, arg UpsertSegmentScanParams) error {
	_, err := q.db.ExecContext(ctx, upsertSegmentScan,
		arg.FileID,
		arg.Fingerprint,
		arg.Audio,
		arg.ScannedAt,
	)
	return err
}
