// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subtitles.sql

package sqlc

import (
	"context"

	"github.com/laterna-project/laterna/internal/domain"
)

const deleteFileFonts = `-- name: DeleteFileFonts :exec
DELETE FROM file_fonts WHERE file_id = ?
`

func (q *Queries) DeleteFileFonts(ctx context.Context, fileID domain.ID) error {
	_, err := q.db.ExecContext(ctx, deleteFileFonts, fileID)
	return err
}

const deleteOrphanFonts = `-- name: DeleteOrphanFonts :many
DELETE FROM fonts
WHERE NOT EXISTS (SELECT 1 FROM file_fonts ff WHERE ff.sha256 = fonts.sha256)
RETURNING sha256, ext
`

type DeleteOrphanFontsRow struct {
	Sha256 string
	Ext    string
}

func (q *Queries) DeleteOrphanFonts(ctx context.Context) ([]DeleteOrphanFontsRow, error) {
	rows, err := q.db.QueryContext(ctx, deleteOrphanFonts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeleteOrphanFontsRow{}
	for rows.Next() {
		var i DeleteOrphanFontsRow
		if err := rows.Scan(&i.Sha256, &i.Ext); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSubtitles = `-- name: DeleteSubtitles :exec
DELETE FROM subtitles WHERE file_id = ?
`

func (q *Queries) DeleteSubtitles(ctx context.Context, fileID domain.ID) error {
	_, err := q.db.ExecContext(ctx, deleteSubtitles, fileID)
	return err
}

const getFont = `-- name: GetFont :one
SELECT sha256, names, ext, size FROM fonts WHERE sha256 = ?
`

func (q *Queries) GetFont(ctx context.Context, sha256 string) (Font, error) {
	row := q.db.QueryRowContext(ctx, getFont, sha256)
	var i Font
	err := row.Scan(
		&i.Sha256,
		&i.Names,
		&i.Ext,
		&i.Size,
	)
	return i, err
}

const getSubtitleSet = `-- name: GetSubtitleSet :one
SELECT file_id, fingerprint, sidecars, extracted_at FROM subtitle_sets WHERE file_id = ?
`

func (q *Queries) GetSubtitleSet(ctx context.Context, fileID domain.ID) (SubtitleSet, error) {
	row := q.db.QueryRowContext(ctx, getSubtitleSet, fileID)
	var i SubtitleSet
	err := row.Scan(
		&i.FileID,
		&i.Fingerprint,
		&i.Sidecars,
		&i.ExtractedAt,
	)
	return i, err
}

const insertFileFont = `-- name: InsertFileFont :exec
INSERT INTO file_fonts (file_id, sha256) VALUES (?, ?) ON CONFLICT DO NOTHING
`

type InsertFileFontParams struct {
	FileID domain.ID
	Sha256 string
}

func (q *Queries) InsertFileFont(ctx context.Context, arg InsertFileFontParams) error {
	_, err := q.db.ExecContext(ctx, insertFileFont, arg.FileID, arg.Sha256)
	return err
}

const insertFont = `-- name: InsertFont :exec
INSERT INTO fonts (sha256, names, ext, size) VALUES (?, ?, ?, ?) ON CONFLICT (sha256) DO NOTHING
`

type InsertFontParams struct {
	Sha256 string
	Names  string
	Ext    string
	Size   int64
}

func (q *Queries) InsertFont(ctx context.Context, arg InsertFontParams) error {
	_, err := q.db.ExecContext(ctx, insertFont,
		arg.Sha256,
		arg.Names,
		arg.Ext,
		arg.Size,
	)
	return err
}

const insertSubtitle = `-- name: InsertSubtitle :exec
INSERT INTO subtitles (file_id, position, stream_idx, path, codec, language, title, is_default, is_forced,
                       is_hearing_impaired, formats, width, height)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSubtitleParams struct {
	FileID            domain.ID
	Position          int64
	StreamIdx         int64
	Path              string
	Codec             string
	Language          string
	Title             string
	IsDefault         int64
	IsForced          int64
	IsHearingImpaired int64
	Formats           string
	Width             int64
	Height            int64
}

func (q *Queries) InsertSubtitle(ctx context.Context, arg InsertSubtitleParams) error {
	_, err := q.db.ExecContext(ctx, insertSubtitle,
		arg.FileID,
		arg.Position,
		arg.StreamIdx,
		arg.Path,
		arg.Codec,
		arg.Language,
		arg.Title,
		arg.IsDefault,
		arg.IsForced,
		arg.IsHearingImpaired,
		arg.Formats,
		arg.Width,
		arg.Height,
	)
	return err
}

const listFileFonts = `-- name: ListFileFonts :many
SELECT f.sha256, f.names, f.ext, f.size
FROM fonts f JOIN file_fonts ff ON ff.sha256 = f.sha256
WHERE ff.file_id = ?
ORDER BY f.sha256
`

func (q *Queries) ListFileFonts(ctx context.Context, fileID domain.ID) ([]Font, error) {
	rows, err := q.db.QueryContext(ctx, listFileFonts, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Font{}
	for rows.Next() {
		var i Font
		if err := rows.Scan(
			&i.Sha256,
			&i.Names,
			&i.Ext,
			&i.Size,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubtitleSetFiles = `-- name: ListSubtitleSetFiles :many
SELECT file_id FROM subtitle_sets
`

func (q *Queries) ListSubtitleSetFiles(ctx context.Context) ([]domain.ID, error) {
	rows, err := q.db.QueryContext(ctx, listSubtitleSetFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []domain.ID{}
	for rows.Next() {
		var file_id domain.ID
		if err := rows.Scan(&file_id); err != nil {
			return nil, err
		}
		items = append(items, file_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubtitles = `-- name: ListSubtitles :many
SELECT file_id, position, stream_idx, path, codec, language, title, is_default, is_forced, is_hearing_impaired, formats, width, height FROM subtitles WHERE file_id = ? ORDER BY position
`

func (q *Queries) ListSubtitles(ctx context.Context, fileID domain.ID) ([]Subtitle, error) {
	rows, err := q.db.QueryContext(ctx, listSubtitles, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subtitle{}
	for rows.Next() {
		var i Subtitle
		if err := rows.Scan(
			&i.FileID,
			&i.Position,
			&i.StreamIdx,
			&i.Path,
			&i.Codec,
			&i.Language,
			&i.Title,
			&i.IsDefault,
			&i.IsForced,
			&i.IsHearingImpaired,
			&i.Formats,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSubtitleSet = `-- name: UpsertSubtitleSet :exec
INSERT INTO subtitle_sets (file_id, fingerprint, sidecars, extracted_at) VALUES (?, ?, ?, ?)
ON CONFLICT (file_id) DO UPDATE
SET fingerprint = excluded.fingerprint, sidecars = excluded.sidecars, extracted_at = excluded.extracted_at
`

type UpsertSubtitleSetParams struct {
	FileID      domain.ID
	Fingerprint string
	Sidecars    string
	ExtractedAt int64
}

func (q *Queries) UpsertSubtitleSet(ctx context.Context, arg UpsertSubtitleSetParams) error {
	_, err := q.db.ExecContext(ctx, upsertSubtitleSet,
		arg.FileID,
		arg.Fingerprint,
		arg.Sidecars,
		arg.ExtractedAt,
	)
	return err
}
