// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: themes.sql

package sqlc

import (
	"context"

	"github.com/laterna-project/laterna/internal/domain"
)

const deleteTheme = `-- name: DeleteTheme :execrows
DELETE FROM themes WHERE id = ? AND built_in = 0
`

func (q *Queries) DeleteTheme(ctx context.Context, id domain.ID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTheme, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTheme = `-- name: GetTheme :one
SELECT id, name, name_key, built_in, tokens, created_at, updated_at FROM themes WHERE id = ?
`

func (q *Queries) GetTheme(ctx context.Context, id domain.ID) (Theme, error) {
	row := q.db.QueryRowContext(ctx, getTheme, id)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameKey,
		&i.BuiltIn,
		&i.Tokens,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getThemeImage = `-- name: GetThemeImage :one
SELECT id, item_id, person_id, theme_id, kind, source, path, remote_url, width, height, blurhash, hash, updated_at FROM images WHERE theme_id = ? AND kind = ?
`

type GetThemeImageParams struct {
	ThemeID *domain.ID
	Kind    string
}

func (q *Queries) GetThemeImage(ctx context.Context, arg GetThemeImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, getThemeImage, arg.ThemeID, arg.Kind)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.PersonID,
		&i.ThemeID,
		&i.Kind,
		&i.Source,
		&i.Path,
		&i.RemoteUrl,
		&i.Width,
		&i.Height,
		&i.Blurhash,
		&i.Hash,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTheme = `-- name: InsertTheme :exec
INSERT INTO themes (id, name, name_key, built_in, tokens, created_at, updated_at) VALUES (?, ?, ?, 0, ?, ?, ?)
`

type InsertThemeParams struct {
	ID        domain.ID
	Name      string
	NameKey   string
	Tokens    string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) InsertTheme(ctx context.Context, arg InsertThemeParams) error {
	_, err := q.db.ExecContext(ctx, insertTheme,
		arg.ID,
		arg.Name,
		arg.NameKey,
		arg.Tokens,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertThemeImage = `-- name: InsertThemeImage :exec
INSERT INTO images (id, theme_id, kind, source, path, width, height, blurhash, hash, updated_at)
VALUES (?, ?, ?, 'upload', ?, ?, ?, ?, ?, ?)
`

type InsertThemeImageParams struct {
	ID        domain.ID
	ThemeID   *domain.ID
	Kind      string
	Path      string
	Width     int64
	Height    int64
	Blurhash  string
	Hash      string
	UpdatedAt int64
}

func (q *Queries) InsertThemeImage(ctx context.Context, arg InsertThemeImageParams) error {
	_, err := q.db.ExecContext(ctx, insertThemeImage,
		arg.ID,
		arg.ThemeID,
		arg.Kind,
		arg.Path,
		arg.Width,
		arg.Height,
		arg.Blurhash,
		arg.Hash,
		arg.UpdatedAt,
	)
	return err
}

const listThemeImages = `-- name: ListThemeImages :many
SELECT id, item_id, person_id, theme_id, kind, source, path, remote_url, width, height, blurhash, hash, updated_at FROM images WHERE theme_id IS NOT NULL
`

func (q *Queries) ListThemeImages(ctx context.Context) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listThemeImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.PersonID,
			&i.ThemeID,
			&i.Kind,
			&i.Source,
			&i.Path,
			&i.RemoteUrl,
			&i.Width,
			&i.Height,
			&i.Blurhash,
			&i.Hash,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThemes = `-- name: ListThemes :many
SELECT id, name, name_key, built_in, tokens, created_at, updated_at FROM themes ORDER BY built_in DESC, name_key
`

func (q *Queries) ListThemes(ctx context.Context) ([]Theme, error) {
	rows, err := q.db.QueryContext(ctx, listThemes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Theme{}
	for rows.Next() {
		var i Theme
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameKey,
			&i.BuiltIn,
			&i.Tokens,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProfileTheme = `-- name: SetProfileTheme :exec
UPDATE profiles SET theme_id = ?, theme_mode = ?, updated_at = ? WHERE id = ?
`

type SetProfileThemeParams struct {
	ThemeID   *domain.ID
	ThemeMode string
	UpdatedAt int64
	ID        domain.ID
}

func (q *Queries) SetProfileTheme(ctx context.Context, arg SetProfileThemeParams) error {
	_, err := q.db.ExecContext(ctx, setProfileTheme,
		arg.ThemeID,
		arg.ThemeMode,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateTheme = `-- name: UpdateTheme :exec
UPDATE themes SET name = ?, name_key = ?, tokens = ?, updated_at = ? WHERE id = ? AND built_in = 0
`

type UpdateThemeParams struct {
	Name      string
	NameKey   string
	Tokens    string
	UpdatedAt int64
	ID        domain.ID
}

func (q *Queries) UpdateTheme(ctx context.Context, arg UpdateThemeParams) error {
	_, err := q.db.ExecContext(ctx, updateTheme,
		arg.Name,
		arg.NameKey,
		arg.Tokens,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertBuiltinTheme = `-- name: UpsertBuiltinTheme :exec
INSERT INTO themes (id, name, name_key, built_in, tokens, created_at, updated_at) VALUES (?, ?, ?, 1, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET name = excluded.name, name_key = excluded.name_key, built_in = 1, tokens = excluded.tokens,
    updated_at = excluded.updated_at
WHERE themes.tokens <> excluded.tokens OR themes.name <> excluded.name
`

type UpsertBuiltinThemeParams struct {
	ID        domain.ID
	Name      string
	NameKey   string
	Tokens    string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) UpsertBuiltinTheme(ctx context.Context, arg UpsertBuiltinThemeParams) error {
	_, err := q.db.ExecContext(ctx, upsertBuiltinTheme,
		arg.ID,
		arg.Name,
		arg.NameKey,
		arg.Tokens,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
